### ISSUE TITLE
Problem firewalld dropping calico traffic on the nft backend

### ISSUE THREAD

**Issue by EricSeynaeve** [firewalld/firewalld#767] opened 2021-03-04 14:37 UTC
**What happened**:
Installed kubernetes using kubespray on Fedora33 systems. Used the Calico CNI on nft and crio container runtime.
Ping between pods worked fine, but tcp traffic between pods on different nodes failed with "no route to host". When check between pods on the same node, things worked fine.

**What you expected to happen**:
tcp traffic between pods services on different nodes should work fine.

**How to reproduce it (as minimally and precisely as possible)**:
- use kubespray to install kubernetes
  - crio backend
  - calico CNI with NFT
- create pods with an http connection on different nodes.
- try to curl the page of one pod from another pod

**Anything else we need to know?**:

I noticed that the calico rules are going through following chain:
```
table ip filter {
        chain FORWARD {
                type filter hook forward priority filter; policy accept;
                 counter packets 645 bytes 98875 jump cali-FORWARD
                  mark and 0x10000 == 0x10000 counter packets 3 bytes 180 accept
        }
}
```
firewalld rules are added to following chain:
```
table inet firewalld {
        chain filter_FORWARD {
                type filter hook forward priority filter + 10; policy accept;
                ct state { established, related } accept
                ct status dnat accept
                iifname "lo" accept
                ip6 daddr { ::/96, ::ffff:0.0.0.0/96, 2002::/24, 2002:a00::/24, 2002:7f00::/24, 2002:a9fe::/32, 2002:ac10::/28, 2002:c0a8::/32, 2002:e000::/19 } reject with icmpv6 type addr-unreachable
                jump filter_FORWARD_IN_ZONES
                jump filter_FORWARD_OUT_ZONES
                ct state { invalid } drop
                reject with icmpx type admin-prohibited
        }
}
```
Notice the difference in priority: `filter` for calico, `filter + 10` for firewalld.

Adding following rule to the firewalld chain solved the issue: `meta mark & 0x00010000 == 0x00010000 oifname "cali*" accept` (mark selection is done for mimicing calico filter logic).

**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`):
- dnf info firewalld
Installed Packages
Name         : firewalld
Version      : 0.8.6
Release      : 1.fc33
Architecture : noarch
Size         : 1.9 M
Source       : firewalld-0.8.6-1.fc33.src.rpm
Repository   : @System
From repo    : updates
Summary      : A firewall daemon with D-Bus interface providing a dynamic firewall
URL          : http://www.firewalld.org
License      : GPLv2+
Description  : firewalld is a firewall service daemon that provides a dynamic customizable
             : firewall with a D-Bus interface.

- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): FirewallBackend=nftables
- OS (e.g: `cat /etc/os-release`): Fedora 33
- Others:
  - kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by EricSeynaeve** [comment] 2021-03-04 14:45
From the [blog post on nftables](https://firewalld.org/2018/07/nftables-backend), I read the following:
> firewalld takes advantage of this feature to add predictability by giving firewalld’s rules _slightly lower_ precedence than iptables and default nftables hook priority values.
(emphasis mine)

I'm still trying to wrap my head round this, but isn't `filter + 10` a higher precedence ? Looking at the example on the [nftables base chain page](https://wiki.nftables.org/wiki-nftables/index.php/Configuring_chains#Base_chain_priority) where an accept in a chain with priority 0 is still dropped in a chain with priority 1.

**Comment by erig0** [comment] 2021-03-04 15:03
> From the [blog post on nftables](https://firewalld.org/2018/07/nftables-backend), I read the following:
> 
> > firewalld takes advantage of this feature to add predictability by giving firewalld’s rules _slightly lower_ precedence than iptables and default nftables hook priority values.
> > (emphasis mine)
> 
> I'm still trying to wrap my head round this, but isn't `filter + 10` a higher precedence ? Looking at the example on the [nftables base chain page](https://wiki.nftables.org/wiki-nftables/index.php/Configuring_chains#Base_chain_priority) where an accept in a chain with priority 0 is still dropped in a chain with priority 1.

Higher number, but lower precedence. Where precedence means: executed first.

In netfliter (kernel) when a packet is ACCEPTed further hooks are still considered. This explains why a priority 0 hook may ACCEPT a packet, but a priority 1 hook may still DROP the packet.

**Comment by erig0** [comment] 2021-03-04 15:05
There is nothing that can be fixed here. This behavior is what is expected when you combine iptables and nftables. It would occur without firewalld (i.e. hand written iptables and nftables rules).

If you want to packets to be accepted by firewalld with FirewallBackend=ntftables, then you can add the relevant interfaces to the `trusted` zone.

**Comment by EricSeynaeve** [comment] 2021-03-04 15:10
So we should then add the `tunl0` and `cali*` interfaces to the `trusted` zone.

**Comment by erig0** [comment] 2021-03-04 15:10
> So we should then add the `tunl0` and `cali*` interfaces to the `trusted` zone.

Yes. That would allow the traffic through firewalld. That means firewalld won't filter that traffic at all. Any filtering/policies will have to be done by Calico.

**Comment by EricSeynaeve** [comment] 2021-03-04 15:11
OK. Thanks.

**Comment by EricSeynaeve** [comment] 2021-03-04 15:13
Completely unrelated, just to improve my English :-)

I was always under the impression that something with a higher precedence would overrule something with a lower precedence. Is that a wrong understanding of the word ?

**Comment by erig0** [comment] 2021-03-04 15:16
> Completely unrelated, just to improve my English :-)
> 
> I was always under the impression that something with a higher precedence would overrule something with a lower precedence. Is that a wrong understanding of the word ?

No. Your understanding is correct. The issue is context. You gave the example of ACCEPT before DROP. The problem is that ACCEPT in netfilter doesn't mean "accept now". It means "accept for _this_ hook, and continue considering further hooks"

Consider the opposite - again with context in mind. DROP before ACCEPT. In this case any hook can DROP a packet before a later hook that tries to ACCEPT. In netfilter DROP means "drop now, do _not_ consider further hooks."

**Comment by erig0** [comment] 2021-03-04 15:18
As for filtering the forward traffic in firewalld.. newer firewalld, v0.9.0+, has native support for forward filtering. This is in Fedora 34 and later.

See this post if interested:
https://firewalld.org/2020/09/policy-objects-introduction

**Comment by erig0** [comment] 2021-03-04 15:19
Closing, because this is not possible to fix.

**Closed by erig0** 2021-03-04 15:19 UTC
Labels: can't fix
