### ISSUE TITLE
Cascading Zones/Subzones

### ISSUE THREAD

**Issue by smcmurray** [firewalld/firewalld#295] opened 2018-02-16 19:35 UTC
Firewalld uses cascading zones, but does not allow the user to configure cascading zones.
Consider:
````
iptables -N INPUT_ZONES
iptables -N Z1
iptables -N Z2

iptables -A INPUT -j INPUT_ZONES

iptables -A INPUT_ZONES -i eth0 -j Z1

iptables -A Z1 -p tcp -m tcp --dport 9999 -m conntrack --ctstate NEW -j ACCEPT
iptables -A Z1 -s 192.168.0.0/16 -j Z2

iptables -A Z2 -p tcp -m tcp --dport 9999 -m conntrack --ctstate NEW -j ACCEPT
````

In this case, Z2 is a "subzone" of Z1. Of course, Z2 could simultaneously be a subzone of Z3, etc if Z3, etc jumpt to Z2. And of course, this could lead to looped logic, etc. but iptables should already have answers to those kinds of challenges.

**Comment by erig0** [comment] 2018-02-19 17:08
> Firewalld uses cascading zones

I don't think that's true. Packets ingress one and only one zone.

Depending on --set-target they can be accepted/dropped/rejected at the end of the zone, or if --set-target=default then the packets fall back to the INPUT chain, but they never continue on to another zone.

**Comment by luizluca** [comment] 2018-04-09 17:45
@erig0 , could we have "RETURN" as zone target? That with a clean way to order zones (not simply using name prefix) would be a powerful feature.

**Comment by erig0** [comment] 2018-04-10 14:31
@luizluca, that would allow it to return to the INPUT_ZONE chain, but there is still no way to order the zones inside the INPUT_ZONE chain.

**Comment by luizluca** [comment] 2018-04-10 16:58
"...with a clean way to order zones" is another new feature not related to this issue. We already can use the zone name prefix for that. There are other issues open related to this.

We could also use network sorting as route table does for ordering zones. It is the most usual way to use nested zones. That order might not be the most optimized way to order zones for specific situations but, at least, anything can be done repeating rules.

I guess implement RETURN might not be a radical change and it could turn source zones into a much usable thing.

**Comment by erig0** [comment] 2019-05-31 14:03
Duplicate of #192.

**Closed by erig0** 2019-05-31 14:03 UTC
Labels: duplicate
