### ISSUE TITLE
Fails on completely new Debian 12 server

### ISSUE THREAD

**Issue by lonix1** [firewalld/firewalld#1184] opened 2023-08-07 04:18 UTC
I also posted to [StackOverflow](https://serverfault.com/q/1140935/473183).

## What happened

My Debian 12 Bookworm VPS was running firewalld 1.3.0-1 without problems. Due to unrelated issues, I had to rebuild the server, and now firewalld fails.

I use ansible, so the configuration should be identical to before. Maybe some apt dependencies have changed in the interim.

## What you expected to happen

I expected it to work without error. But it doesn't even start.

## How to reproduce it (as minimally and precisely as possible)

To troubleshoot more easily, I started from scratch:
- I created a **brand new VPS** with my hosting company; debian 12
- I logged in as root
- `$ apt install firewalld --yes`
- `$ systemctl status firewalld.service`

```
ERROR: 'python-nftables' failed: internal:0:0-0: Error: No such file or directory; did you mean chain ‘nat_PREROUTING’ in table inet ‘firewalld’?
Error: Could not process rule: No such file or directory
Error: No such file or directory; did you mean chain ‘nat_POSTROUTING’ in table inet ‘firewalld’?
Error: Could not process rule: No such file or directory
...etc.
```

My intention is to use iptables instead of nftables (a docker limitation), so:
- I edited `/etc/firewalld/firewalld.config` and replaced `FirewallBackend=nftables` with `FirewallBackend=iptables`
- `$ systemctl restart firewalld.service`
- `$ systemctl status firewalld.service`

```sh
ERROR: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.8.9 (nf_tables): 
CHAIN_ADD failed (No such file or directory): chain PREROUTING
RULE_APPEND failed (No such file or directory): rule in chain PREROUTING
RULE_APPEND failed (No such file or directory): rule in chain PREROUTING
CHAIN_ADD failed (No such file or directory): chain POSTROUTING
RULE_APPEND failed (No such file or directory): rule in chain POSTROUTING
RULE_APPEND failed (No such file or directory): rule in chain POSTROUTING
CHAIN_ADD failed (No such file or directory): chain OUTPUT
RULE_APPEND failed (No such file or directory): rule in chain OUTPUT
RULE_APPEND failed (No such file or directory): rule in chain OUTPUT
...etc.
```

## Anything else we need to know?

I don't understand as it was working before. And as you can see this is a **completely new server**, with nothing installed and nothing else configured. I expected it to work "out of the box".

What could be the reason?

### Firewalld Version

1.3.0-1

### Firewalld Backend

iptables

### Linux distribution

debian 12 bookworm

### Linux kernel version

6.1.0-10-amd64

## Other information

Thank you!

**Comment by erig0** [comment] 2023-08-07 17:22
It's not expected. It looks like a failure of the firewall backends and not firewalld itself.

That could be caused by security policies, e.g. SELinux. A reboot could cause them to be reloaded.

**Comment by biuld** [comment] 2023-08-22 03:32
I've encountered same problems. However, after reboot, mine is still not working. The systemd status says ok, but underneath firewalld is not running and its gui firewalld-config also cannot connect to it. Is there any way to resolve this problem? I have a wild guess that would it be caused by nftables 's default blank ruleset?

**Comment by biuld** [comment] 2023-08-28 02:48
In fact, I was running debian 12 with patched kernel on a single board computer. During the weekend, I've tested more scenarios. For example, I've tried different versions of kernel (6.1.x series) and different distro rootfs. And I get the same failure every time. Therefore I think the patch applied is whom to be blamed.
I don't know if firewalld and the nftables underneath are rely on some specific kernel features which might be disabled by the patch. If not, please do reopen it.

**Comment by erig0** [comment] 2023-08-28 13:15
@lonix1 , can you confirm your VPS is using a stock Debian kernel? Some VPS's actually provide a custom kernel, e.g. OpenVZ.

**Comment by erig0** [comment] 2023-08-28 14:04
Can you show `uname -a` output?

**Comment by erig0** [comment] 2023-08-28 19:04
Hrm. That looks like a vanilla Debian kernel and not a VPS specific one.

Can you share the kernel config? It's usually at `/boot/config-$(uname -r)`

**Comment by erig0** [comment] 2023-08-29 13:40
> (To repeat my note above, the workaround is simply to reboot... for anyone who encounters this issue.)

A reboot fixed your issue?

That does sound like an SELinux policy was reloaded, but as you say, you're not using SELinux.

**Comment by erig0** [comment] 2023-08-29 13:41
I'm closing this bug as there is no action that can be taken; nor is there evidence of a firewalld bug.

**Closed by erig0** 2023-08-29 13:41 UTC
Labels: triage
