### ISSUE TITLE
Enh. Req.: Ability to add comments to entries?

### ISSUE THREAD

**Issue by jamesdavidhoward** [firewalld/firewalld#269] opened 2017-12-02 03:14 UTC
In - for example - an IPset entry of type hash:mac, it would be helpful if I could associate a comment field with the MAC addresses entered.  By the time some dozen MAC addresses are listed, it becomes nearly impossible to keep track of what MAC belongs to what device.  (MAC addresses are entered because portable devices get wildly varying IP addresses as they move about.)

**Comment by leonbloy** [comment] 2018-01-19 21:24
Related: https://serverfault.com/questions/893112/migrating-from-iptables-to-firewalld-commenting-rules

**Comment by erig0** [comment] 2018-01-22 14:31
Duplicate of #194.

**Closed by erig0** 2018-01-22 14:31 UTC
Labels: duplicate, enhancement
