### ISSUE TITLE
firewalld doesn't work when IPv6 is disabled

### ISSUE THREAD

**Issue by F-i-f** [firewalld/firewalld#496] opened 2019-06-21 18:10 UTC
When IPv6 is disabled with `ipv6=disable` on the kernel command line, firewalld doesn't work.
```
 systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-06-21 11:06:03 PDT; 2s ago
     Docs: man:firewalld(1)
 Main PID: 15545 (firewalld)
    Tasks: 2 (limit: 19100)
   Memory: 21.6M
   CGroup: /system.slice/firewalld.service
           └─15545 /usr/bin/python3 /usr/sbin/firewalld --nofork --nopid

Jun 21 11:06:02 mica systemd[1]: Starting firewalld - dynamic firewall daemon...
Jun 21 11:06:03 mica systemd[1]: Started firewalld - dynamic firewall daemon.
Jun 21 11:06:03 mica firewalld[15545]: WARNING: ip6tables not usable, disabling IPv6 firewall.
Jun 21 11:06:03 mica firewalld[15545]: ERROR: UNKNOWN_ERROR: 'ip6tables' backend does not exist
Jun 21 11:06:03 mica firewalld[15545]: ERROR: COMMAND_FAILED: UNKNOWN_ERROR: 'ip6tables' backend does not exist
Jun 21 11:06:03 mica firewalld[15545]: ERROR: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.8.2 (legacy): goto 'PRE_public' is not a chain
                                       
                                       Error occurred at line: 2
                                       Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Jun 21 11:06:03 mica firewalld[15545]: ERROR: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.8.2 (legacy): goto 'PRE_public' is not a chain
                                       
                                       Error occurred at line: 2
                                       Try `iptables-restore -h' or 'iptables-restore --help' for more information.
```

This is on Fedora 30 with firewalld-0.6.3-2.fc30.noarch.

**Comment by erig0** [comment] 2019-06-22 18:25
Duplicate of #491, which is already fixed.

**Closed by erig0** 2019-06-22 18:25 UTC
