### ISSUE TITLE
Logging with ULOG?

### ISSUE THREAD

**Issue by rkarlsba** [firewalld/firewalld#268] opened 2017-11-30 13:10 UTC
Hi all

It's good to have logging working, indeed, but I wonder why firewalld doen't support using the ULOG target instead of LOG. This may not be everyone's choice, but for some it can be a good way to get the firewall logs away from potentially more important logs to be practically visible, for instance in the dmesg command.

I looked at the code, and couldn't find any traces of ULOG, and nothing on google either.

So - has this been discussed?

**Comment by erig0** [comment] 2018-03-14 17:21
dupe of #259.

**Closed by erig0** 2018-03-14 17:21 UTC
