### ISSUE TITLE
Disable default conntrack rules

### ISSUE THREAD

**Issue by adsr** [firewalld/firewalld#1153] opened 2023-06-30 20:25 UTC
Hello. Is there a way to configure firewalld in such a way that it doesn't use conntrack at all? conntrack can harm performance on high volume server applications.

On a vanilla Rocky Linux 9 host (which ships with firewalld enabled), the default config produces the following nft ruleset:

```
# nft list ruleset
table inet firewalld {
        chain mangle_PREROUTING {
                type filter hook prerouting priority mangle + 10; policy accept;
                jump mangle_PREROUTING_ZONES
        }

        chain mangle_PREROUTING_POLICIES_pre {
                jump mangle_PRE_policy_allow-host-ipv6
        }

        chain mangle_PREROUTING_ZONES {
                iifname "eth0" goto mangle_PRE_trusted
                goto mangle_PRE_trusted
        }

        chain mangle_PREROUTING_POLICIES_post {
        }

        chain nat_PREROUTING {
                type nat hook prerouting priority dstnat + 10; policy accept;
                jump nat_PREROUTING_ZONES
        }

        chain nat_PREROUTING_POLICIES_pre {
                jump nat_PRE_policy_allow-host-ipv6
        }

        chain nat_PREROUTING_ZONES {
                iifname "eth0" goto nat_PRE_trusted
                goto nat_PRE_trusted
        }

        chain nat_PREROUTING_POLICIES_post {
        }

        chain nat_POSTROUTING {
                type nat hook postrouting priority srcnat + 10; policy accept;
                jump nat_POSTROUTING_ZONES
        }

        chain nat_POSTROUTING_POLICIES_pre {
        }

        chain nat_POSTROUTING_ZONES {
                oifname "eth0" goto nat_POST_trusted
                goto nat_POST_trusted
        }

        chain nat_POSTROUTING_POLICIES_post {
        }

        chain nat_OUTPUT {
                type nat hook output priority -90; policy accept;
                jump nat_OUTPUT_POLICIES_pre
                jump nat_OUTPUT_POLICIES_post
        }

        chain nat_OUTPUT_POLICIES_pre {
        }

        chain nat_OUTPUT_POLICIES_post {
        }

        chain filter_PREROUTING {
                type filter hook prerouting priority filter + 10; policy accept;
                icmpv6 type { nd-router-advert, nd-neighbor-solicit } accept
                meta nfproto ipv6 fib saddr . mark . iif oif missing drop
        }

        chain filter_INPUT {
                type filter hook input priority filter + 10; policy accept;
                ct state { established, related } accept
                ct status dnat accept
                ct state invalid drop
                iifname "lo" accept
                jump filter_INPUT_ZONES
                reject with icmpx admin-prohibited
        }

        chain filter_FORWARD {
                type filter hook forward priority filter + 10; policy accept;
                ct state { established, related } accept
                ct status dnat accept
                ct state invalid drop
                iifname "lo" accept
                ip6 daddr { ::/96, ::ffff:0.0.0.0/96, 2002::/24, 2002:a00::/24, 2002:7f00::/24, 2002:a9fe::/32, 2002:ac10::/28, 2002:c0a8::/32, 2002:e000::/19 } reject with icmpv6 addr-unreachable
                jump filter_FORWARD_ZONES
                reject with icmpx admin-prohibited
        }

        chain filter_OUTPUT {
                type filter hook output priority filter + 10; policy accept;
                ct state { established, related } accept
                oifname "lo" accept
                ip6 daddr { ::/96, ::ffff:0.0.0.0/96, 2002::/24, 2002:a00::/24, 2002:7f00::/24, 2002:a9fe::/32, 2002:ac10::/28, 2002:c0a8::/32, 2002:e000::/19 } reject with icmpv6 addr-unreachable
                jump filter_OUTPUT_POLICIES_pre
                jump filter_OUTPUT_POLICIES_post
        }

        chain filter_INPUT_POLICIES_pre {
                jump filter_IN_policy_allow-host-ipv6
        }

        chain filter_INPUT_ZONES {
                iifname "eth0" goto filter_IN_trusted
                goto filter_IN_trusted
        }

        chain filter_INPUT_POLICIES_post {
        }

        chain filter_FORWARD_POLICIES_pre {
        }

        chain filter_FORWARD_ZONES {
                iifname "eth0" goto filter_FWD_trusted
                goto filter_FWD_trusted
        }

        chain filter_FORWARD_POLICIES_post {
        }

        chain filter_OUTPUT_POLICIES_pre {
        }

        chain filter_OUTPUT_POLICIES_post {
        }

        chain filter_IN_trusted {
                jump filter_INPUT_POLICIES_pre
                jump filter_IN_trusted_pre
                jump filter_IN_trusted_log
                jump filter_IN_trusted_deny
                jump filter_IN_trusted_allow
                jump filter_IN_trusted_post
                jump filter_INPUT_POLICIES_post
                accept
        }

        chain filter_IN_trusted_pre {
        }

        chain filter_IN_trusted_log {
        }

        chain filter_IN_trusted_deny {
        }

        chain filter_IN_trusted_allow {
        }

        chain filter_IN_trusted_post {
        }

        chain nat_POST_trusted {
                jump nat_POSTROUTING_POLICIES_pre
                jump nat_POST_trusted_pre
                jump nat_POST_trusted_log
                jump nat_POST_trusted_deny
                jump nat_POST_trusted_allow
                jump nat_POST_trusted_post
                jump nat_POSTROUTING_POLICIES_post
        }

        chain nat_POST_trusted_pre {
        }

        chain nat_POST_trusted_log {
        }

        chain nat_POST_trusted_deny {
        }

        chain nat_POST_trusted_allow {
        }

        chain nat_POST_trusted_post {
        }

        chain filter_FWD_trusted {
                jump filter_FORWARD_POLICIES_pre
                jump filter_FWD_trusted_pre
                jump filter_FWD_trusted_log
                jump filter_FWD_trusted_deny
                jump filter_FWD_trusted_allow
                jump filter_FWD_trusted_post
                jump filter_FORWARD_POLICIES_post
                accept
        }

        chain filter_FWD_trusted_pre {
        }

        chain filter_FWD_trusted_log {
        }

        chain filter_FWD_trusted_deny {
        }

        chain filter_FWD_trusted_allow {
                oifname "eth0" accept
        }

        chain filter_FWD_trusted_post {
        }

        chain nat_PRE_trusted {
                jump nat_PREROUTING_POLICIES_pre
                jump nat_PRE_trusted_pre
                jump nat_PRE_trusted_log
                jump nat_PRE_trusted_deny
                jump nat_PRE_trusted_allow
                jump nat_PRE_trusted_post
                jump nat_PREROUTING_POLICIES_post
        }

        chain nat_PRE_trusted_pre {
        }

        chain nat_PRE_trusted_log {
        }

        chain nat_PRE_trusted_deny {
        }

        chain nat_PRE_trusted_allow {
        }

        chain nat_PRE_trusted_post {
        }

        chain mangle_PRE_trusted {
                jump mangle_PREROUTING_POLICIES_pre
                jump mangle_PRE_trusted_pre
                jump mangle_PRE_trusted_log
                jump mangle_PRE_trusted_deny
                jump mangle_PRE_trusted_allow
                jump mangle_PRE_trusted_post
                jump mangle_PREROUTING_POLICIES_post
        }

        chain mangle_PRE_trusted_pre {
        }

        chain mangle_PRE_trusted_log {
        }

        chain mangle_PRE_trusted_deny {
        }

        chain mangle_PRE_trusted_allow {
        }

        chain mangle_PRE_trusted_post {
        }

        chain filter_IN_policy_allow-host-ipv6 {
                jump filter_IN_policy_allow-host-ipv6_pre
                jump filter_IN_policy_allow-host-ipv6_log
                jump filter_IN_policy_allow-host-ipv6_deny
                jump filter_IN_policy_allow-host-ipv6_allow
                jump filter_IN_policy_allow-host-ipv6_post
        }

        chain filter_IN_policy_allow-host-ipv6_pre {
        }

        chain filter_IN_policy_allow-host-ipv6_log {
        }

        chain filter_IN_policy_allow-host-ipv6_deny {
        }

        chain filter_IN_policy_allow-host-ipv6_allow {
                icmpv6 type nd-neighbor-advert accept
                icmpv6 type nd-neighbor-solicit accept
                icmpv6 type nd-router-advert accept
                icmpv6 type nd-redirect accept
        }

        chain filter_IN_policy_allow-host-ipv6_post {
        }

        chain nat_PRE_policy_allow-host-ipv6 {
                jump nat_PRE_policy_allow-host-ipv6_pre
                jump nat_PRE_policy_allow-host-ipv6_log
                jump nat_PRE_policy_allow-host-ipv6_deny
                jump nat_PRE_policy_allow-host-ipv6_allow
                jump nat_PRE_policy_allow-host-ipv6_post
        }

        chain nat_PRE_policy_allow-host-ipv6_pre {
        }

        chain nat_PRE_policy_allow-host-ipv6_log {
        }

        chain nat_PRE_policy_allow-host-ipv6_deny {
        }

        chain nat_PRE_policy_allow-host-ipv6_allow {
        }

        chain nat_PRE_policy_allow-host-ipv6_post {
        }

        chain mangle_PRE_policy_allow-host-ipv6 {
                jump mangle_PRE_policy_allow-host-ipv6_pre
                jump mangle_PRE_policy_allow-host-ipv6_log
                jump mangle_PRE_policy_allow-host-ipv6_deny
                jump mangle_PRE_policy_allow-host-ipv6_allow
                jump mangle_PRE_policy_allow-host-ipv6_post
        }

        chain mangle_PRE_policy_allow-host-ipv6_pre {
        }

        chain mangle_PRE_policy_allow-host-ipv6_log {
        }

        chain mangle_PRE_policy_allow-host-ipv6_deny {
        }

        chain mangle_PRE_policy_allow-host-ipv6_allow {
        }

        chain mangle_PRE_policy_allow-host-ipv6_post {
        }
}
```

If I remove the conntrack-related rules in `filter_(INPUT|FORWARD|OUTPUT)`:

```
# nft list ruleset >dump
# nft flush ruleset
# grep -vw ct dump | nft -f -
```

conntrack entries stop accumulating (`wc -l /proc/net/nf_conntrack`). This also probably breaks firewalld, but that's the end effect I'm looking for.

Blacklisting the related kernel modules seems to break firewalld. (Or at least it emits errors and doesn't produce any netfilters.)

I've attempted various invocations of `firewall-cmd --direct --add-rule ... --notrack` but I seem to either block traffic entirely or fail to disable conntrack. Maybe this is related to https://github.com/firewalld/firewalld/issues/1056.

Completely disabling firewalld of course has the desired effect, but that's a blunt solution.

Any tips? Thanks.

**Comment by erig0** [comment] 2023-07-05 14:08
No. firewalld is stateful by design. Everything in the project assumes stateful filtering. Without the stateful rules you would need to add rules in both directions. Beyond that there are probably other things that won't work.

If you're are concerned about performance, then consider looking at enabling the [software fast path](https://firewalld.org/2023/05/nftables-flowtable).

**Comment by erig0** [comment] 2023-07-05 14:09
Closing as this is specifically a non-goal.

**Closed by erig0** 2023-07-05 14:09 UTC
