### ISSUE TITLE
problem with firewall-config

### ISSUE THREAD

**Issue by adavida** [firewalld/firewalld#378] opened 2018-08-23 11:31 UTC
on my openSuse Tumbleweed, firewall-config does not work anymore 
on launch firewall-config  
```
(firewall-config:20214): Gtk-WARNING **: 13:09:47.425: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(firewall-config:20214): Gtk-WARNING **: 13:09:47.425: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(firewall-config:20214): Gtk-WARNING **: 13:09:47.425: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
<class 'gi.repository.Gtk.TreeIter'> -<Gtk.TreeIter object at 0x7f8c856e7a08 (GtkTreeIter at 0x55e82a288560)>-
<class 'str'> -docker0-
Traceback (most recent call last):
  File "/usr/bin/firewall-config", line 8095, in <module>
    app = FirewallConfig()
  File "/usr/bin/firewall-config", line 1386, in __init__
    self.connection_changed()
  File "/usr/bin/firewall-config", line 1692, in connection_changed
    self.update_active_zones()
  File "/usr/bin/firewall-config", line 2466, in update_active_zones
    connection, zone ])
  File "/usr/lib64/python3.6/site-packages/gi/overrides/Gtk.py", line 1245, in append
    return self._do_insert(parent, -1, row)
  File "/usr/lib64/python3.6/site-packages/gi/overrides/Gtk.py", line 1237, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib64/python3.6/site-packages/gi/overrides/Gtk.py", line 876, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib64/python3.6/site-packages/gi/overrides/Gtk.py", line 894, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib64/python3.6/site-packages/gi/overrides/GObject.py", line 218, in __init__
    self.set_value(py_value)
  File "/usr/lib64/python3.6/site-packages/gi/overrides/GObject.py", line 274, in set_value
    (py_value, type(py_value)))
ValueError: Expected string but got False<class 'bool'>
```

I found a solution, i change on my opensuse the file **/usr/bin/firewall-config** (**/firewalld/src/firewall-config.in** on githut repo )
ligne 2459-2464 :
```
                 self.bindingsStore.append(
                    self.connectionsIter,
                    [ "%s (%s)\n<small>%s</small>" % (
                        connection_name, ",".join(_interfaces),
                        _("Zone: %s") % zone),
                      connection, zone ])
```
 to
```
                 self.bindingsStore.append(
                    self.connectionsIter,
                    [ "%s (%s)\n<small>%s</small>" % (
                        connection_name, ",".join(_interfaces),
                        _("Zone: %s") % zone),
                      connection, str(zone) ])
```
now this work.
I find that the problem is "zone" is perfect in type bools

**Comment by erig0** [comment] 2018-08-23 12:43
Duplicate of #370.

**Closed by erig0** 2018-08-23 12:43 UTC
