### ISSUE TITLE
Request to be able to add comments

### ISSUE THREAD

**Issue by novadarkstar** [firewalld/firewalld#489] opened 2019-05-07 18:48 UTC
I see that there has already been a request to add comments to ipsets, I would like to generalize this request to be able to add notes/comments to any field that is manually entered. For example, if I want to open a port I would like to add a comment about what the port is used for. Or if I add a new IP address, what machine/purpose is it being used for. This would help a LOT to administer complex firewalls.

**Comment by erig0** [comment] 2021-11-22 12:57
Duplicate of #194.

**Closed** 2021-11-22 13:38 UTC
Labels: duplicate
