### ISSUE TITLE
Built-in zones can be disabled

### ISSUE THREAD

**Issue by unknowndevQwQ** [firewalld/firewalld#1091] opened 2023-03-04 06:07 UTC
### What would you like to be added

After attempting to delete a built-in zone with --delete-zone, any action on the specified zone will act as if the zone had been deleted, and an attempt to undo this action requires only --add-zone on the zone

### Why is this needed

I've found that some zones are actually not needed during use, but they can't be removed, and part of the reason for disabling them is to make the zones look neater

**Comment by erig0** [comment] 2023-03-06 14:09
This is a duplicate of #897.

**Closed** 2023-05-26 18:03 UTC
Labels: duplicate, feature
