### ISSUE TITLE
Rich Rule Masquerade inverted source-destination in Forward Chain

### ISSUE THREAD

**Issue by simon3z** [firewalld/firewalld#278] opened 2017-12-31 13:33 UTC
A rich-rule masquerade:

```
firewall-cmd --permanent --zone=public \
  --add-rich-rule 'rule family="ipv4" source address="192.168.2.0/24" masquerade'
```

```
<?xml version="1.0" encoding="utf-8"?>
<zone>
  <short>Public</short>
  ...
  <rule family="ipv4">
    <source address="192.168.2.0/24"/>
    <masquerade/>
  </rule>
</zone>
```

currently is generating a reversed source-destination rule in the FWDO chain:

```
-A POST_public_allow -s 192.168.2.0/24 ! -o lo -j MASQUERADE
-A FWDO_public_allow -d 192.168.2.0/24 -m conntrack --ctstate NEW -j ACCEPT
```

I expected instead that the resulting FWDO rule would have used the same source and destination of the POSTROUTING MASQUERADE rule:

```
-A FWDO_public_allow -s 192.168.2.0/24 -m conntrack --ctstate NEW -j ACCEPT
```

The [relevant code](https://github.com/firewalld/firewalld/blob/b20345ad5db13cf9a8ca8f5cb036ef526ab6693b/src/firewall/core/fw_zone.py#L1306-L1311) even has a comment on the need for source and destination inversion:

```python
    command = [ ]
    # reverse source/destination !
    self.__rule_source(rule.destination, command)
    self.__rule_destination(rule.source, command)
    command += [ "-m", "conntrack", "--ctstate", "NEW",
                 "-j", "ACCEPT" ]
```

I cannot understand why this inversion is needed though.
Even in a real-case scenario this is not allowing the relevant traffic to pass correctly.
On the other hand the same rule with non-reversed source and destination works as expected.

cc @t-woerner

**Comment by erig0** [comment] 2018-07-18 13:14
Duplicate of issue #80.

**Closed by erig0** 2018-07-18 13:14 UTC
