### ISSUE TITLE
Firewalld do not delete created ipset from system's ipset

### ISSUE THREAD

**Issue by mpolitaev** [firewalld/firewalld#573] opened 2020-01-29 21:56 UTC
Hello team!

I created an ipset by firewalld:
`firewall-cmd --permanent --new-ipset=myset --type=hash:ip`
then reload firewalld to apply changes:
`firewall-cmd --reload`

I see created ipset in system's ipset by
```
ipset -L
Name: myset
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 120
References: 0
Number of entries: 0
Members:
```
As well I see ipset in output `firewall-cmd --permanent --get-ipsets`

Then i am going to delete fresh created ipset (let's assume i created it by mistake with wrong name):
`firewall-cmd --permanent --delete-ipset=myset`
But even after reload:
`firewall-cmd --reload`

I still see my ipset "myset" in output of `ipset -L`
```
Name: myset
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 120
References: 0
Number of entries: 0
Members:
```
But no see in `firewall-cmd --permanent --get-ipsets` anymore.

Is it ok that i still see in `ipset -L` deleted ipset in `firewalld`? If this ok will it be cause of possible conflict(s) in future?

**Comment by erig0** [comment] 2020-01-30 00:19
This is a duplicate of #330.

> Is it ok that i still see in ipset -L deleted ipset in firewalld? If this ok will it be cause of possible conflict(s) in future?

It is probably okay. Nothing is using the ipset. It will not cause conflicts with ipsets used by firewalld.

**Closed** 2020-01-30 00:19 UTC
Labels: duplicate

**Comment by mpolitaev** [comment] 2020-01-30 05:24
@erig0 Sorry, didn't saw #330 
There suggested make make `firewall-cmd --reload` or `systemctl restart firewalld`, what is not helped in my case (actually i think not only in my) and i still see "deleted" ipset in output `ipset -L`
FYI
