### ISSUE TITLE
firewalld with nftables and docker

### ISSUE THREAD

**Issue by fansari** [firewalld/firewalld#666] opened 2020-07-09 10:03 UTC
Is firewalld meant to be usable with nftables backend and docker? 

I could not get in working so far - I also tried with direct rules for the FORWARD chain stuff but this also did not work (seems direct rules still try to use iptables for whatever reason).

If there is a way to use it like this I will try again - otherwise I will use nftables directly.

**Comment by erig0** [comment] 2020-07-09 12:19
Duplicate of #534. Also see moby/libnetwork#2548 for docker changes to integrate better.

**Closed by erig0** 2020-07-09 12:19 UTC
