### ISSUE TITLE
deleting permanent configuration out-of-band causes in memory configuration to be out of sync with on-disk configuration

### ISSUE THREAD

**Issue by fanicolini** [firewalld/firewalld#1043] opened 2022-11-08 08:54 UTC
### What happened

If you try to add a new rich rule, file <zone.xml> is not created under /etc/firewalld/zones folder and rule lost.

firewall-cmd --permanent --add-rich-rule "rule family=\"ipv4\" icmp-type name=\"echo-reply\" drop"

### What you expected to happen

File  /etc/firewalld/zones/<zone>.xml should be created and added the following lines:

  <rule family="ipv4">
    <icmp-type name="echo-reply"/>
    <drop/>
  </rule>

### How to reproduce it (as minimally and precisely as possible)

1. set default zone public
2. if present, remove  /etc/firewalld/zones/public.xml
3. run commnd: firewall-cmd --permanent --add-rich-rule "rule family=\"ipv4\" icmp-type name=\"echo-reply\" drop"
4. file /etc/firewalld/zones/public.xml is not created

### Firewalld Version

0.9.3

### Firewalld Backend

nftables

### Linux distribution

Red Hat Enterprise Linux 8.6

### Linux kernel version

4.18.0-372.26.1.el8_6.x86_64

**Comment by erig0** [comment] 2022-11-08 13:39
Did you happen to get this message?
```
Warning: ALREADY_ENABLED: rule family=ipv4 icmp-type name=echo-reply drop
```

You're removing the config file out-of-band of firewalld. However, firewalld maintains an in memory version of the permanent configuration. This avoids having to parse the file every time.

When you add the rich rule a second time the in memory config is identical so you get the ALREADY_ENABLED warning above. Additionally the zone is not re-written on disk because it did not change as far as firewalld knows.

```
[root@vm-local-rhel9-2 ~]# ls -al /etc/firewalld/zones/public.xml
ls: cannot access '/etc/firewalld/zones/public.xml': No such file or directory
[root@vm-local-rhel9-2 ~]# firewall-cmd --permanent --list-all --zone public
public
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns ssh
  ports: 
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
        rule family="ipv4" icmp-type name="echo-reply" drop
```

If you remove the configuration file out-of-band, then you need to reload firewalld afterwards.
```
# rm /etc/firewalld/zones/public.xml
# firewall-cmd --reload
```

**Comment by erig0** [comment] 2022-11-08 18:06
> Hi, thank you for the prompt answer. I see the warning message you showed, so the problem is the in memory config.

No, I'm suggesting this is not a bug. Something, i.e. `rm`, deleted firewalld's configuration.

> 1) I cannot '--reload' the configuration before properly configuring all the firewall rules.This is to avoid to change the runtime config that can cause some connection disruption.

Firewalld allows existing connections to pass traffic during a `--reload`. See commit 67aa1ce6a965f617774f5af7b8a28782a41a4cbd.

2) The same does not happen if I add a service to the public zone.In this case /etc/firewalld/zones/public.xml is properly created. How can this different behavior be explained? I think there is a bug on --add-rich-rule command

It does for me.

```
[root@vm-local-rhel9-1 build]# firewall-cmd --permanent --add-service https --zone public
success
[root@vm-local-rhel9-1 build]# cat /etc/firewalld/zones/public.xml
<?xml version="1.0" encoding="utf-8"?>
<zone>
  <short>Public</short>
  <description>For use in public areas. You do not trust the other computers on networks to not harm your computer. Only selected incomin
g connections are accepted.</description>
  <service name="ssh"/>
  <service name="mdns"/>
  <service name="dhcpv6-client"/>
  <service name="https"/>
</zone>
[root@vm-local-rhel9-1 build]# rm /etc/firewalld/zones/public.xml
rm: remove regular file '/etc/firewalld/zones/public.xml'? y
[root@vm-local-rhel9-1 build]# firewall-cmd --permanent --add-service https --zone public
Warning: ALREADY_ENABLED: https
success
[root@vm-local-rhel9-1 build]# ls /etc/firewalld/zones/public.xml
ls: cannot access '/etc/firewalld/zones/public.xml': No such file or directory
```

**Comment by erig0** [comment] 2022-11-08 18:19
I'm closing this an "won't fix" for reasons in my top comment.

**Closed by erig0** 2022-11-08 18:19 UTC
Labels: won't fix
