### ISSUE TITLE
order of INPUT_ZONES_SOURCE rules

### ISSUE THREAD

**Issue by brownjtb** [firewalld/firewalld#166] opened 2016-11-10 21:54 UTC
I make use of several custom source zones and in RHEL 7.2 (firewalld version 0.3.9), I was able to control the order within "INPUT_ZONES_SOURCE" by ensuring that my zones were named numerically... for example:

   chain INPUT_ZONES_SOURCES
   target       source   destination
   IN_00_it   192.168.2.10  0.0.0.0/0
   IN_10_wrk   192.168.2.0/24   0.0.0.0/0
   IN_20_vpn   192.168.3.0/22   0.0.0.0

However, since firewalld was upgraded (0.4.3.2) in RHEL 7.3 this no longer appears to the case.  I have tried renaming my zones and even changed the order that they are created, but I can not seem to configure in a way that will guarantee that my rules will be processed in a specific order.  For example, the above may now look like the following:

   chain INPUT_ZONES_SOURCES
   target       source   destination
   IN_10_wrk   192.168.2.0/24   0.0.0.0/0
   IN_00_it   192.168.2.10  0.0.0.0/0
   IN_20_vpn   192.168.3.0/22   0.0.0.0

There appears to be a fundamental change in how zones are created and added to the "iptables" rules.  For example, if a packet satisfies the "IN_10_wrk" rules in the second example above, it will not reach the "IN_00_it" rule.  Is there a command-line flag or argument that allows the functionality to revert back where the the zones are created and listed in numerical order (such as in RHEL 7.2, firewalld 0.3.9)?

I believe I have seen comments in other messages that suggest zones should not overlap.  However, I do not believe that this is a restriction imposed within IPtables.  With numerical/alphabetical naming, I can control the behavior of my rules, but this no longer appears to be possible with the latest RHEL upgrade.

Is there a way to force the ordering of zones as was the case in earlier versions?  I know that I can remove "firewalld" and manually configure "iptables" or roll-back to version 0.3.9, but before I decide on either of those two options, I thought I would check to see if restricting zone order is possible now in version 0.4.3.2?   Is this something that may be possible in future releases?

**Comment by apenney** [comment] 2016-12-28 15:08
@brownjtb Did you ever figure out a solution for this?  Friend of mine has run into the same exact problem!

**Comment by brownjtb** [comment] 2016-12-28 15:43
No, not in a way that would allow for some overlapping.

I prefer having the rules follow some sort of alphabetical or numerical order as it would give me some control on the ordering - even an order based on listing "most-specific" subnets (source zones) first would help.  However, the only solution I came up with was to develop my rules to ensure that there is never any overlap.   I did consider disabling "firewalld" and go strictly with "iptables", but for my system, which is not very complex, I simply reworked my source-zone definitions to ensure no overlap.

**Comment by rstreet-ossg** [comment] 2017-01-15 21:23
I ended up working around this by using a set of direct rules for the cases where there were overlapping source ranges.

**Comment by t-woerner** [comment] 2017-02-10 15:39
@brownjtb: I am sorry that the transaction model is resulting in this for you. I have just seen that a normal dict has been used for transactions, which does not have an order. If speed is not that impotant for you, then you could set "IndividualCalls=yes" in the firewalld.conf file.

Here is a patch that would solve the issue in firewalld: https://github.com/t-woerner/firewalld/commit/7bbe82ef4ce391af68dfb5299d1c2b1f944b77be

**Comment by todoleza** [comment] 2017-02-10 16:09
a rhel 7 bug was created to address the issue: [rhbz1421222](https://bugzilla.redhat.com/show_bug.cgi?id=1421222).

**Comment by unikmhz** [comment] 2017-04-05 03:40
Unfortunately this issue persists, even when 7bbe82e is applied. ```IndividualCalls=yes``` didn't help either.

Running CentOS 7.3, with 0.4.3.2-8.1.el7_3.2 firewalld packages.

**Comment by unikmhz** [comment] 2017-04-05 04:08
At least at daemon start-up, the issue is apparently fixed by patching ```core/fw_zone.py```:

Remove:
```python
self._zones = { }
```
Substitute by:
```python
self._zones = LastUpdatedOrderedDict()
```

**Comment by t-woerner** [comment] 2017-04-05 08:26
@unikmhz When do you see a change in the order?

**Comment by unikmhz** [comment] 2017-04-05 08:41
Right after firewalld restart (via ```systemd restart firewalld``` command).

**Comment by t-woerner** [comment] 2017-04-05 08:43
O.k., now I see why you get into this with 0.4.3.2-8.1.el7_3.2. In newer versions there is an additional patch that fixes the order of zone and zone parts, services, etc. This is 2f42e7cbea1d0e1b05e91827f8b695a6e1e107f6
Please add this patch also. Zones are applied always as a sorted list in apply_zones now. Even after reloading.

**Comment by t-woerner** [comment] 2017-04-05 08:44
An additional change in fw_zone is then not needed.

**Comment by unikmhz** [comment] 2017-04-05 08:54
I can confirm 7bbe82e + 2f42e7c works. Thank you, much appreciated.

**Comment by t-woerner** [comment] 2017-04-05 08:55
You are welcome

**Comment by erig0** [comment] 2018-08-10 20:46
This was fixed according to this comment: https://github.com/firewalld/firewalld/issues/166#issuecomment-291797288

**Closed by erig0** 2018-08-10 20:46 UTC
