### ISSUE TITLE
firewall-cmd --set-log-denied=all and dmesg

### ISSUE THREAD

**Issue by holger24** [firewalld/firewalld#855] opened 2021-09-14 12:58 UTC
Hello,

when setting firewall-cmd --set-log-denied=all all denied messages will go to dmesg as well and it makes dmesg unusable if you have lots of those hitting the server. I think if one could configure firewalld to use NFLOG instead of LOG, this would not be a problem. Or is there another method with firewalld to set it up that denied messages do not get shown in dmesg?

Thanks,
Holger

**Comment by erig0** [comment] 2021-09-14 14:29
You can use a rich rule to rate limit logging. If placed at the end of the zone it will occur before the zone's catch-all target (`--set-target`).
Example to log at most 10 per minute:
```
firewall-cmd --zone public --add-rich-rule='rule priority=32767 log limit value=10/m'
```

**Comment by holger24** [comment] 2021-09-15 06:39
Thank you for tip with rate limit, but I forgot to mention that I need the log for psad. And I would still see them in dmesg. I would like to keep dmesg 'clean' from these messages.

I have seen #587 and #720 but did not see them appear in a new release. What is the reason that they do not get picked up by firewalld?

**Comment by erig0** [comment] 2021-09-15 11:54
> I have seen #587 and #720 but did not see them appear in a new release. What is the reason that they do not get picked up by firewalld?

Bandwidth on my end. I flagged it as priority. I'll try to review it again next week.

**Comment by erig0** [comment] 2021-09-15 11:54
Closing this bug as a duplicate of #587.

**Closed by erig0** 2021-09-15 11:54 UTC
Labels: question
