### ISSUE TITLE
"FirewallD is not running" firewalld shutdown unexpectedly

### ISSUE THREAD

**Issue by simmonHuong** [firewalld/firewalld#322] opened 2018-04-07 07:36 UTC
Hello,I was pretty sure I have ran these command `systemctl start firewalld && systemctl enable firewalld` and they took effect,work as expected deny or allow some port on some ip for several months.

But today when I run `firewall-cmd --list-all` it returns `FirewallD is not running`,I have experienced the same issue before.I can't find any reason why it is stopped.Below is some information about my vps.
`uname -a`
```
Linux hostname1 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
`systemctl status firewalld`
```
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Mon 2018-03-12 10:12:04 CST; 3 weeks 5 days ago
     Docs: man:firewalld(1)
 Main PID: 504 (code=killed, signal=KILL)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```
`tail -n 50 firewalld`
```
2018-03-09 10:09:24 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.18.0.3 -d 172.18.0.3 --dport 80 -j MASQUERADE' failed: iptables: No chain/target/match by that name.

2018-03-09 10:09:33 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 9090 -j DNAT --to-destination 172.18.0.5:80 ! -i br-476afb62d58b' failed: iptables: No chain/target/match by that name.

2018-03-09 10:09:33 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER ! -i br-476afb62d58b -o br-476afb62d58b -p tcp -d 172.18.0.5 --dport 80 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2018-03-09 10:09:33 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.18.0.5 -d 172.18.0.5 --dport 80 -j MASQUERADE' failed: iptables: No chain/target/match by that name.

2018-03-09 10:09:33 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 9091 -j DNAT --to-destination 172.18.0.6:80 ! -i br-476afb62d58b' failed: iptables: No chain/target/match by that name.

2018-03-09 10:09:33 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER ! -i br-476afb62d58b -o br-476afb62d58b -p tcp -d 172.18.0.6 --dport 80 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2018-03-09 10:09:34 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.18.0.6 -d 172.18.0.6 --dport 80 -j MASQUERADE' failed: iptables: No chain/target/match by that name.

2018-03-09 21:02:54 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 9090 -j DNAT --to-destination 172.18.0.5:80 ! -i br-476afb62d58b' failed: iptables: No chain/target/match by that name.

2018-03-09 21:02:54 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER ! -i br-476afb62d58b -o br-476afb62d58b -p tcp -d 172.18.0.5 --dport 80 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2018-03-09 21:02:54 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.18.0.5 -d 172.18.0.5 --dport 80 -j MASQUERADE' failed: iptables: No chain/target/match by that name.

2018-03-10 15:50:40 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 9099 -j DNAT --to-destination 172.18.0.8:80 ! -i br-476afb62d58b' failed: iptables: No chain/target/match by that name.

2018-03-10 15:50:40 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER ! -i br-476afb62d58b -o br-476afb62d58b -p tcp -d 172.18.0.8 --dport 80 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2018-03-10 15:50:40 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.18.0.8 -d 172.18.0.8 --dport 80 -j MASQUERADE' failed: iptables: No chain/target/match by that name.

2018-03-10 15:50:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 9091 -j DNAT --to-destination 172.18.0.6:80 ! -i br-476afb62d58b' failed: iptables: No chain/target/match by that name.

2018-03-10 15:50:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER ! -i br-476afb62d58b -o br-476afb62d58b -p tcp -d 172.18.0.6 --dport 80 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2018-03-10 15:50:43 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.18.0.6 -d 172.18.0.6 --dport 80 -j MASQUERADE' failed: iptables: No chain/target/match by that name.

2018-03-10 15:50:45 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 9090 -j DNAT --to-destination 172.18.0.5:80 ! -i br-476afb62d58b' failed: iptables: No chain/target/match by that name.

2018-03-10 15:50:45 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER ! -i br-476afb62d58b -o br-476afb62d58b -p tcp -d 172.18.0.5 --dport 80 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2018-03-10 15:50:45 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.18.0.5 -d 172.18.0.5 --dport 80 -j MASQUERADE' failed: iptables: No chain/target/match by that name.

2018-03-10 19:42:37 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 902 -j DNAT --to-destination 172.18.0.2:80 ! -i br-476afb62d58b' failed: iptables: No chain/target/match by that name.

2018-03-10 19:42:37 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER ! -i br-476afb62d58b -o br-476afb62d58b -p tcp -d 172.18.0.2 --dport 80 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2018-03-10 19:42:37 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.18.0.2 -d 172.18.0.2 --dport 80 -j MASQUERADE' failed: iptables: No chain/target/match by that name.

2018-03-10 19:42:38 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER -p tcp -d 0/0 --dport 9091 -j DNAT --to-destination 172.18.0.6:80 ! -i br-476afb62d58b' failed: iptables: No chain/target/match by that name.

2018-03-10 19:42:38 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER ! -i br-476afb62d58b -o br-476afb62d58b -p tcp -d 172.18.0.6 --dport 80 -j ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

2018-03-10 19:42:38 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C POSTROUTING -p tcp -s 172.18.0.6 -d 172.18.0.6 --dport 80 -j MASQUERADE' failed: iptables: No chain/target/match by that name.

```

Don't know if it is appropriate to ask here,but could some help me with these questions?
- How can I debug this kind of issue?
- I am worried about whether firewalld stop unexpectedly would expose my vps into the unsafe internet world?
- When I run `iptables -L` there is a lot rules there,did this mean iptables still take effect?
- Is it necessary to monitor firewalld?

**Comment by simmonHuong** [comment] 2018-04-07 09:06
maybe this link can give more information https://github.com/moby/moby/issues/16816,I do have docker running in my vps.

**Comment by erig0** [comment] 2018-04-09 15:59
> How can I debug this kind of issue?

Please check dmesg for errors and lsmod to make sure necessary modules are loaded (nf_conntrack, ip_tables, iptable_nat, etc)

> I am worried about whether firewalld stop unexpectedly would expose my vps into the unsafe internet world?

Looks like the failure happens immediately on service start.

> When I run iptables -L there is a lot rules there,did this mean iptables still take effect?

Can you share this output? Please show all tables (-t option).

**Comment by simmonHuong** [comment] 2018-05-15 05:56
@erig0 So sorry,It's a bit long time since I am waiting for the situation to come again.But seems till now every thing goes well.Will notify you next time I come across .

**Comment by erig0** [comment] 2018-06-01 19:20
Okay. Closing. Please reopen if you can reproduce.

**Closed by erig0** 2018-06-01 19:20 UTC
