### ISSUE TITLE
systemd unit file: possible dependency loop

### ISSUE THREAD

**Issue by mohag** [firewalld/firewalld#414] opened 2018-10-26 16:34 UTC
I'm not sure if this is a bug in firewalld. The default `firewalld.service` file which gets used in the Debian/Ubuntu package end up with this dependency loops involving `firewalld.service`. (I have my theories, but I'm not sure why that is the case)

On stopping:
```
Oct 26 09:43:51 hostname systemd[1]: firewalld.service: Found ordering cycle on sysinit.target/stop
Oct 26 09:43:51 hostname systemd[1]: firewalld.service: Found dependency on cloud-init.service/stop
Oct 26 09:43:51 hostname systemd[1]: firewalld.service: Found dependency on networking.service/stop
Oct 26 09:43:51 hostname systemd[1]: firewalld.service: Found dependency on network-pre.target/stop
Oct 26 09:43:51 hostname systemd[1]: firewalld.service: Found dependency on firewalld.service/stop
Oct 26 09:43:51 hostname systemd[1]: firewalld.service: Job sysinit.target/stop deleted to break ordering cycle starting with firewalld.service/stop
```

On starting:
```
Oct 26 09:44:34 hostname kernel: [   14.321552] systemd[1]: sysinit.target: Found ordering cycle on cloud-init.service/start
Oct 26 09:44:34 hostname kernel: [   14.327144] systemd[1]: sysinit.target: Found dependency on networking.service/start
Oct 26 09:44:34 hostname kernel: [   14.332163] systemd[1]: sysinit.target: Found dependency on network-pre.target/start
Oct 26 09:44:34 hostname kernel: [   14.336991] systemd[1]: sysinit.target: Found dependency on firewalld.service/stop
Oct 26 09:44:34 hostname kernel: [   14.341466] systemd[1]: sysinit.target: Found dependency on basic.target/start
Oct 26 09:44:34 hostname kernel: [   14.345469] systemd[1]: sysinit.target: Found dependency on sockets.target/start
```

Fedora (and likely as a result RHEL and CentOS) have their [own unit file](https://src.fedoraproject.org/rpms/firewalld/blob/56e929d1f4e6841dd961343d0053abd68bd911a2/f/firewalld.service), which does not exhibit this problem.

Replacing the unit file with this version (A mix of the default on and the Fedora one), seems to resolve the problem: (Mainly non-forking and keeping some of the dependencies)
```
[Unit]
Description=Firewall dynamic change handling daemon
After=syslog.target
After=dbus.service
After=polkit.service
Conflicts=iptables.service ip6tables.service ebtables.service ipset.service
Documentation=man:firewalld(1)

[Service]
EnvironmentFile=-/etc/sysconfig/firewalld
ExecStart=/usr/sbin/firewalld --nofork $FIREWALLD_ARGS
ExecReload=/bin/kill -HUP $MAINPID
# supress to log debug and error output also to /var/log/messages
StandardOutput=null
StandardError=null
Type=dbus
BusName=org.fedoraproject.FirewallD1
KillMode=mixed

[Install]
WantedBy=multi-user.target
Alias=dbus-org.fedoraproject.FirewallD.service
```

My guess of what might be a factor mainly involve these two lines: (I don't know systemd well enough to be certain)
```
Before=network-pre.target
Wants=network-pre.target
```

Another possibility is that some of the DefaultDependencies interact with the ones added...

I know that removing FirewallD solves the problem, as does dropping the Fedora-based unit file in `/etc/systemd/system/firewalld.service`.

**Comment by mohag** [comment] 2018-10-26 16:57
I see git-blame refers to this: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

My guess is that `cloud-init-local.service` is the other interfering service here...

It has this:
```
DefaultDependencies=no
Wants=network-pre.target
After=systemd-remount-fs.service
Before=NetworkManager.service
Before=network-pre.target
Before=shutdown.target
Before=sysinit.target
Conflicts=shutdown.target
```

**Comment by erig0** [comment] 2019-02-14 14:19
@mbiebl, any thoughts here?

**Comment by mbiebl** [comment] 2019-02-14 14:28
firewalld.service does not have `DefaultDependencies=yes`, so is started *after* sysinit.target.
At the same time it orders itself before network-pre.target.
cloud-init-local.service orders itself before network-pre.target and sysinit.target. It is thus impossible to satisfy this set of dependencies/orderings.

**Comment by erig0** [comment] 2019-02-14 17:05
> firewalld.service does not have DefaultDependencies=yes, so is started after sysinit.target.

SYSTEMD.UNIT(5) says this is the default value.

**Comment by mbiebl** [comment] 2019-02-14 17:10
> SYSTEMD.UNIT(5) says this is the default value.

this way a typo, I obviously meant: firewalld.service does not have `DefaultDependencies=no`, so the implied default is `yes`, so it is started *after* sysinit.target.

**Comment by tpgxyz** [comment] 2019-05-30 11:21
I found issue that firewalld.service is taking 4 seconds of boot time. Checked with latest 0.6.4 release

Here is the boot cricital chain with systemd.mask=firewalld.service in grub2 boot parameters

```
[root@localhost live]# systemd-analyze critical-chain
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

graphical.target @4.3457s
└─sddm.service @4.3310s +13ms
  └─systemd-user-sessions.service @3.9152s +20ms
    └─network.target @3.9138s
      └─systemd-resolved.service @1.7714s +2.141s
        └─systemd-tmpfiles-setup.service @1.5284s +23ms
          └─local-fs.target @1.5187s
            └─local-fs-pre.target @1.5186s
              └─lvm2-monitor.service @234.8ms +1.283s
                └─dm-event.socket @217.3ms
                  └─-.mount
                    └─system.slice
                      └─-.slice
```

Here is default boot

```
[root@localhost live]# systemd-analyze critical-chain
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

graphical.target @4.7426s
└─multi-user.target @4.7424s
  └─firewalld.service @2.4115s +2.330s
    └─polkit.service @1.5953s +814ms
      └─basic.target @1.5937s
        └─sockets.target @1.5918s
          └─pcscd.socket @1.5916s
            └─sysinit.target @1.5738s
              └─systemd-timesyncd.service @1.5716s
                └─systemd-tmpfiles-setup.service @1.5431s +25ms
                  └─local-fs.target @1.5416s
                    └─local-fs-pre.target @1.5416s
                      └─lvm2-monitor.service @255.9ms +1.285s
                        └─dm-event.socket @254.8ms
                          └─-.mount
                            └─systemd-journald.socket
                              └─-.mount
                                └─...
```

**Comment by rizerzero** [comment] 2022-02-22 09:24
Hi guys, I have the same problem on Debian 11, when I install firewalld.   the service networking sometimes does not start after a reboot. (also, I have no more logs on networking after installing firewalld)  

``` root@node1:~# journalctl -b | egrep "Found|Breaking"
Feb 22 09:00:20  systemd[1]: sysinit.target: Found ordering cycle on cloud-init.service/start
Feb 22 09:00:20  systemd[1]: sysinit.target: Found dependency on networking.service/start
Feb 22 09:00:20  systemd[1]: sysinit.target: Found dependency on network-pre.target/start
Feb 22 09:00:20  systemd[1]: sysinit.target: Found dependency on firewalld.service/start
Feb 22 09:00:20  systemd[1]: sysinit.target: Found dependency on basic.target/start
Feb 22 09:00:20  systemd[1]: sysinit.target: Found dependency on sockets.target/start
Feb 22 09:00:20  systemd[1]: sysinit.target: Found dependency on docker.socket/start
Feb 22 09:00:20  systemd[1]: sysinit.target: Found dependency on sysinit.target/start```

**Comment by mbiebl** [comment] 2022-02-22 12:00
@rizerzero I assume your problem is gone by uninstalling cloud-init

**Comment by mbiebl** [comment] 2022-02-22 12:04
you basically have two unit files with conflicting requirements.
cloud-init.service want's to start before sysinit.target and firewalld.service after sysinit.target.
Both are tied together via network-pre.target. 
Why cloud-init.service needs to order itself before network-pre.target I don't know.
systemd.special says this to network-pre.target:
```
    network-pre.target
           This passive target unit may be pulled in by services that want to run before any network is set up, for example for the purpose of
           setting up a firewall. All network management software orders itself after this target, but does not pull it in.
```
I don't think cloud-init set's up any firewall rules, but I might be wrong.

**Comment by rizerzero** [comment] 2022-02-22 12:52
@mbiebl Thank you for your quick response, the issue is that cloud-init is installed on all my instances provided by my hosting provider. 

What I had to do was to uninstall firewalld understand the source of my problem. I have spent a long time to make it work with docker and Debian ^^' so I hope this will be fixed.

Any idea why I have no more logs on the networking service after installing firewalld ?

```
Feb 18 16:34:24 host ifup[1601]: Waiting for DAD... Done
Feb 18 16:34:24 host systemd[1]: Finished Raise network interfaces.
Feb 18 18:08:41 host systemd[1]: cloud-init.service: Found ordering cycle on sysinit.target/stop
Feb 18 18:08:41 host systemd[1]: cloud-init.service: Found dependency on dbus.socket/stop
Feb 18 18:08:41 host systemd[1]: cloud-init.service: Found dependency on dbus.service/stop
Feb 18 18:08:41 host systemd[1]: cloud-init.service: Found dependency on firewalld.service/stop
Feb 18 18:08:41 host systemd[1]: cloud-init.service: Found dependency on network-pre.target/stop
Feb 18 18:08:41 host systemd[1]: cloud-init.service: Found dependency on networking.service/stop
Feb 18 18:08:41 host systemd[1]: cloud-init.service: Found dependency on cloud-init.service/stop
Feb 18 18:08:41 host systemd[1]: cloud-init.service: Job sysinit.target/stop deleted to break ordering cycle startin>
```

**Comment by blackboxsw** [comment] 2022-03-07 19:43
> you basically have two unit files with conflicting requirements. cloud-init.service want's to start before sysinit.target and firewalld.service after sysinit.target. Both are tied together via network-pre.target. Why cloud-init.service needs to order itself before network-pre.target I don't know. systemd.special says this to network-pre.target:

Thanks for this investigation and context here. The `cloud-init-local.service` service is used as the earliest boot stage ([init-local stage](https://cloudinit.readthedocs.io/en/latest/topics/boot.html#local)) during which cloud-init can discover a viable datasource or cloud-platform.  `cloud-init-local.service` needs to run `Before=network-pre.target` because a datasource frequently provides cloud-init with [network configuration directives](https://cloudinit.readthedocs.io/en/latest/topics/network-config.html) which needs to be written to the filesystem before networking services are initially brought up by systemd networking services/units. Writing network config files early allows cloud-init to avoid tearing down and restarting network during early boot after network is already online. Other units declaring a `Before=networking-pre.target` might also introduce this ordering cycle if that unit has After= declarations that conflict with cloud-init-local needing to be before network-pre and after sysinit.target as @mbiebl mentioned https://github.com/firewalld/firewalld/issues/414#issuecomment-463646901.  

One thing to document here from your Debian environment for clarity is how defaultdependencies are being represented on the system for both cloud-init-local.service and firewalld.service.

```bash
systemctl show -p Requires,Wants,Requisite,BindsTo,PartOf,Before,After cloud-init-local.service
systemctl show -p Requires,Wants,Requisite,BindsTo,PartOf,Before,After firewalld.service
```

I wonder if one of the following resolves this on your system:
  1. Setting `[Unit] DefaultDependencies=no` and a `[Install] WantedBy=sysinit.target`in firewalld.service.
  2. Setting firewalld.service be set to `Before=network.target` instead of `Before=network-pre.target`  (it's what ufw systemd unit does)
  3. cloud-init-local.service Unit configuration could be ordered `Before=firewalld.target` on Debian (I believe [rockylinux does this](https://git.rockylinux.org/staging/rpms/cloud-init/-/blob/r8/SOURCES/0001-Add-initial-redhat-setup.patch) already)

**Comment by blackboxsw** [comment] 2022-03-07 19:48
This is also likely represented by this upstream cloud-int bug https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1956629

**Comment by bigon** [comment] 2022-03-08 08:00
On my machine I've the following cycle:

```
[    1.643638] systemd[1]: sysinit.target: Found ordering cycle on cloud-init.service/start
[    1.645482] systemd[1]: sysinit.target: Found dependency on networking.service/start
[    1.647274] systemd[1]: sysinit.target: Found dependency on network-pre.target/start
[    1.649010] systemd[1]: sysinit.target: Found dependency on firewalld.service/start
[    1.650718] systemd[1]: sysinit.target: Found dependency on dbus.service/start
[    1.652294] systemd[1]: sysinit.target: Found dependency on basic.target/start
[    1.654033] systemd[1]: sysinit.target: Found dependency on sysinit.target/start
[    1.655528] systemd[1]: sysinit.target: Job cloud-init.service/start deleted to break ordering cycle starting with sysinit.target/start
```

```
root@XXX:~# systemctl show -p Requires,Wants,Requisite,BindsTo,PartOf,Before,After cloud-init-local.service
Requires=system.slice -.mount
Requisite=
Wants=network-pre.target
BindsTo=
PartOf=
Before=sysinit.target shutdown.target NetworkManager.service cloud-config.target network-pre.target cloud-init.service
After=systemd-remount-fs.service hv_kvp_daemon.service systemd-journald.socket system.slice -.mount
root@XXX:~# systemctl show -p Requires,Wants,Requisite,BindsTo,PartOf,Before,After firewalld.service
Requires=dbus.socket sysinit.target system.slice
Requisite=
Wants=network-pre.target
BindsTo=
PartOf=
Before=shutdown.target multi-user.target fail2ban.service network-pre.target
After=polkit.service basic.target dbus.service sysinit.target dbus.socket system.slice
```

**Comment by mbiebl** [comment] 2022-03-08 09:57
I'd say this issue is diagnosed sufficiently.

Now it just needs a proper solution (either in cloud-init or firewalld)

**Comment by mbiebl** [comment] 2022-03-08 09:58
> 3\. cloud-init-local.service Unit configuration could be ordered `Before=firewalld.target` on Debian (I believe [rockylinux does this](https://git.rockylinux.org/staging/rpms/cloud-init/-/blob/r8/SOURCES/0001-Add-initial-redhat-setup.patch) already)

Please avoid orderings on explicit implementations if they can be avoided.

**Comment by mbiebl** [comment] 2022-03-08 10:06
> `cloud-init-local.service` needs to run `Before=network-pre.target` because a datasource frequently provides cloud-init with [network configuration directives](https://cloudinit.readthedocs.io/en/latest/topics/network-config.html) which needs to be written to the filesystem before networking services are initially brought up by systemd networking services/units. Writing network config files early allows cloud-init to avoid tearing down and restarting network during early boot after network is already online.

This feels a bit like cloud-init is misusing network-pre.target for this purpose, at least when reading the systemd.special man page which says this target should be used for something like firewalls (which firewalld is, but cloud-init isn't).

If cloud-init wants to provide configuration for networking management services (like NetworkManager, systemd-networkd, ifupdown, you name it), I assume it has eplicit support for any of those services and maybe should order itself specifically before those services it supports?

**Comment by erig0** [comment] 2022-03-08 18:43
> If cloud-init wants to provide configuration for networking management services (like NetworkManager, systemd-networkd, ifupdown, you name it), I assume it has eplicit support for any of those services and maybe should order itself specifically before those services it supports?

That sounds reasonable to me.

I don't know enough about systemd units to argue about this either way.

**Comment by mbiebl** [comment] 2022-03-08 21:22
@erig0 I guess this could be addressed from both sides for extra robustness:
cloud-init reviews its usage of network-pre.target and firewalld considers using DefaultDependencies=no

**Comment by rizerzero** [comment] 2022-04-07 08:41
This issue forced me to stop using firewalld :(

**Comment by erig0** [comment] 2022-04-07 12:05
> This issue forced me, unfortunately, to stop using firewalld :(

Could you try using `DefaultDependencies=no` in the firewalld service as indicated by @mbiebl above?

**Comment by erig0** [comment] 2022-04-07 12:30
> Unfortunately, using DefaultDependencies=no won't be easy
> 
> See https://lists.freedesktop.org/archives/systemd-devel/2022-March/047538.html

Thanks for discussing it with the systemd folks. Sounds like it's possible, but difficult and would require functional code changes to firewalld to handle dbus not being available.

To be honest, the later would make firewalld more robust. So on it's own it's not a bad change.

**Comment by michaelw730** [comment] 2022-04-07 13:05
Hi all,

I think I've come across the same/similar issue.  This conversation has really helped me understand what may be happening.

I'm building a Debian 10 image on AWS as a base image for my projects and I wanted firewalld on by default.  VMs created from the image weren't having the key pair transferred over on launch so I couldn't log in via ssh.  It looks like the cloud-init scripts aren't being fully applied if firewalld is enabled (when I go through the logs comparing a broken vm to a working vm).  After 3 days of investigation (enabling/disabling firewalld and various rules) some of the VMs did have the keys transferred when previously the same image didn't have the keys.

I've added
`After=cloud-init.service`
to the firewalld service and it seems to work better.  Unfortunately I don't know systemd/firewalld/cloud-init well enough to know if this is the right solution.  It also might not work on other distros in the same way.

Thanks.

Michael

**Comment by mohag** [comment] 2022-04-07 16:42
> This issue forced me, unfortunately, to stop using firewalld :(

My unit file (based on Fedora's one) from [the initial post](https://github.com/firewalld/firewalld/issues/414#issue-374459890) in `/etc/systemd/system` should allow it to work... (It would be interesting to see why Fedora is using a unit file so different from upstream.

**Comment by rizerzero** [comment] 2022-04-07 17:14
I can't tell I understand all the details around this issue, and I would have certainly modified a package behavior myself if it was not my firewall, I mean it's a sensitive thing right? I love firewalld, but it seems like it's not much the case in linux the community.
Maybe I have high expectations because it's a package related to security. that's why I personally decided to get back to basics and use iptables.

**Comment by erig0** [comment] 2022-04-07 18:19
> My unit file (based on Fedora's one) from [the initial post](https://github.com/firewalld/firewalld/issues/414#issue-374459890) in `/etc/systemd/system` should allow it to work...

I think this is best solution.

Drop:
```
Before=network-pre.target
Wants=network-pre.target
```

Add:
```
After=syslog.target
```

**Comment by erig0** [comment] 2022-04-07 18:59
Although, I wonder about things that talk to firewalld: NetworkManager, podman, libvirt.

**Comment by erig0** [comment] 2022-04-12 13:21
@mbiebl, any thoughts on my previous 2 comments?

**Comment by mbiebl** [comment] 2022-04-12 15:42
> Before=network-pre.target
> Wants=network-pre.target

Hm, not sure I like that. network-pre.target is supposed to be used by firewall providers

**Comment by erig0** [comment] 2022-04-18 12:59
@mohag, @michaelw730, @mbiebl, please review/test #946. It simply adds `After=cloud-init.service`. The explicit ordering is not ideal, but it should address the immediate issue.

**Closed** 2022-04-26 19:31 UTC
Labels: medium, hard, workaround

**Comment by erig0** [comment] 2022-04-26 19:33
This has been fixed upstream, but **users should still file a bug with their distribution** so the distribution's unit file gets updated.

**Comment by rizerzero** [comment] 2022-04-26 19:37
Wonderful

**Comment by mbiebl** [comment] 2022-04-26 19:44
I'm still of the opinion that this is an issue in cloud-init which should not hook into network-pre.target

**Comment by mbiebl** [comment] 2022-04-26 19:45
> Is adding `After=cloud-init.service` enough? That would at least avoid all the work mentioned in the systemd-devel thread, i.e. turning firewalld into an early boot service.

It's a dependency loop, so I don't think an explicit ordering helps.

**Comment by mbiebl** [comment] 2022-04-26 19:52
> 2\. Setting firewalld.service be set to `Before=network.target` instead of `Before=network-pre.target`  (it's what ufw systemd unit does)

Hm, I don't think that's true, see https://git.launchpad.net/ufw/tree/debian/ufw.service?h=debian/master

**Comment by michaelw730** [comment] 2022-04-27 22:25
I've tested this on AWS for debian 9, ubuntu 1804 and ubuntu 2004.  It's a similar error on each but ubuntu 20.04 it's a bit different - the ordering issue with the firewalld.service:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/85802865/165641109-ec8cdf8c-44e3-4c84-a13c-b56f3a3157a4.png">

@erig0 did you test on AWS/Azure/GCP or locally?  I can test it again on another platform if you did.  Maybe it is something to do with the way the cloud distros have been set up (by using cloud-init).

**Comment by erig0** [comment] 2022-04-29 18:58
@michaelw730, are you manually updating the `firewalld.service` on those distributions?

That's what I tested on an Ubuntu 20.04 VM.

**Comment by michaelw730** [comment] 2022-05-04 15:55
Hi @erig0 
I'm using Ansible to install firewalld, copying over the new version of the file, rebooting the server, then checking the syslog - just so that we can automate this process.  I'm sure it would be the same if it was just done manually though,

Thanks.

Michael

**Comment by erig0** [comment] 2022-05-27 13:00
> Hi @erig0 I'm using Ansible to install firewalld, copying over the new version of the file, rebooting the server, then checking the syslog - just so that we can automate this process. I'm sure it would be the same if it was just done manually though,

I don't know why. I guess we can revert the service file change if it doesn't work for you. I'll reopen this bug after I revert the change.

I'm open to ideas from distribution package maintainers on how to fix this.

**Comment by rvandegrift** [comment] 2022-12-16 07:17
The Debian cloud team received #[1025618](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025618), which is a report of the cloud-init side of this bug.  I tried to follow @mbiebl's suggestion, but it's not quite right - I think there's some confusion regarding the different service units that cloud-init provides.

- `cloud-init-local.service` has `Before=network-pre.target`, but is not involved in the cycles.  The cycle details posted above only involve `cloud-init.service`.
   - the debian bug has a nice python script to find cycles in  `systemd-analyze dot --order` output.
- `cloud-init.service` has no explicit order with `network-pre.target`, but it does have `Before=sysinit.target`.

The closest I could get to Michael's suggestion is dropping `Before=sysinit.target` from `cloud-init.service` - but this will break cloud-init's disk setup features (see cloud-init rev `80f5ec4b` which introduces `Before=basic.target`).

**Comment by mbiebl** [comment] 2022-12-16 08:04
@rvandegrift 
If I see this correctly though, `cloud-init.service` has both a `Wants/After=cloud-init-local.service` and `Before=sysinit.target`. So it effectively forces `cloud-init-local.service` to start before `sysinit.target` and therefor `network-pre.target` as well. firewalld.service does not have `DefaultDependencies=no` so is started after `sysinit.target`.
This is where I see the conflicting requirements. Do I miss something?

**Comment by mbiebl** [comment] 2022-12-16 10:12
Afaics, this is not easily fixable (on both sides): After talking to systemd upstream, turning firewalld.service into an early boot service might be tricky (due to its dependency on dbus) :
https://lists.freedesktop.org/archives/systemd-devel/2022-March/047538.html
```
I doubt you can do that. Thing is that firewalld uses D-Bus, and
services that do D-Bus will have a hard time to run during early boot.
```

And if I understand you correctly, you can't easily drop the `Before=sysinit.target` from `cloud-init.service`?
Then again, I see  that `cloud-init.service` tries to be an early boot service (`DefaultDependencies=no`, `Before=sysinit.target`) and on the other hand has dependencies like 
```
# setting hostname via hostnamectl depends on dbus, which otherwise
# would not be guaranteed at this point.
After=dbus.service
```
in its cloud-init.service.tmpl. So it's questinable, whether `cloud-init.service` can actually be safely turned into an early boot service. As the existing bug shows, this is probably not the case

**Comment by rvandegrift** [comment] 2022-12-16 22:43
Hi @mbiebl, thanks for your help.

> If I see this correctly , cloud-init.service has both a Wants/After=cloud-init-local.service and Before=sysinit.target. So it effectively forces cloud-init-local.service to start before sysinit.target and therefor network-pre.target as well. firewalld.service does not have DefaultDependencies=no so can only be started after sysinit.target.
This is where I see the conflicting requirements. Do I miss something?

No, I think you're correct - I just meant that debian's `cloud-init.service` doesn't have an explict `Before=network-pre.target` that can be removed.

> Then again, I see that cloud-init.service tries to be an early boot service (DefaultDependencies=no, Before=sysinit.target) and on the other hand has dependencies like
> ```
> # setting hostname via hostnamectl depends on dbus, which otherwise
> # would not be guaranteed at this point.
> After=dbus.service
> ```
> in its cloud-init.service.tmpl. So it's questinable, whether cloud-init.service can actually be safely turned into an early boot service. As the existing bug shows, this is probably not the case

Agreed, for distros where cloud-init uses `hostnamectl` (rhel, arch, suse, photon).  On debian the hostname is written to `/etc/hostname`, so we don't need dbus - and don't have `After=dbus.service`.  Of course that doesn't help with the cycle.

I don't have any bright ideas for moving forward, but I'll take this back to the cloud team and see what other folks think.  Thanks again.

**Comment by cidrbl0ck** [comment] 2023-01-31 16:38
Hi all, I just encountered this issue on one of our prod servers that' s been running for over 3 weeks w/o issue. Same dmsg error stating:
`[    3.612096] systemd[1]: network-pre.target: Job firewalld.service/start deleted to break ordering cycle starting with network-pre.target/start`

Ubuntu 22.04.1 AWS EC2 
AMI: ami-02f3416038bdb17fb
FirewallD from Ubu repos [1.1.1-1ubuntu1]

@erig0  I assume since you reverted it, that [@erig0
[fix(systemd): order Before network.target](https://github.com/firewalld/firewalld/commit/797234e232ecb680a8e65e709b04400308773ff6) …](https://github.com/firewalld/firewalld/commit/797234e232ecb680a8e65e709b04400308773ff6) did not solve the issue (or invited other problems)?

**Comment by twoodcock** [comment] 2023-06-20 04:24
I am an outsider and I am not sure I fully understand the circumstances, but I'm faced with this issue.

If I understand the problem, the reason firewalld wants to complete its start up before the network is so it can block traffic based on the server's defined rules before the network is established.

Is it possible to establish a non-permissive firewall initially, then follow up with a firewalld.post-network target that establishes the permissive firewall rules?

This might just change the timing of the race condition though, so maybe not a solution.

**Comment by sneko** [comment] 2024-09-14 00:51
Hi, I read the entire thread and I get there were discussions on both sides... but is an official solution 6 years after? Or does it still require to patch a service order to make it working?

On my side I'm on Debian v12, and facing:
```
Sep 14 00:22:02 xxxxxxxx systemd[1]: sysinit.target: Found ordering cycle on dbus.socket/stop
Sep 14 00:22:02 xxxxxxxx systemd[1]: sysinit.target: Found dependency on polkit.service/stop
Sep 14 00:22:02 xxxxxxxx systemd[1]: sysinit.target: Found dependency on firewalld.service/stop
Sep 14 00:22:02 xxxxxxxx systemd[1]: sysinit.target: Found dependency on network-pre.target/stop
Sep 14 00:22:02 xxxxxxxx systemd[1]: sysinit.target: Found dependency on systemd-networkd.service/stop
Sep 14 00:22:02 xxxxxxxx systemd[1]: sysinit.target: Found dependency on systemd-networkd-wait-online.service/stop
Sep 14 00:22:02 xxxxxxxx systemd[1]: sysinit.target: Found dependency on cloud-init.service/stop
Sep 14 00:22:02 xxxxxxxx systemd[1]: sysinit.target: Found dependency on sysinit.target/stop
Sep 14 00:22:02 xxxxxxxx systemd[1]: sysinit.target: Job dbus.socket/stop deleted to break ordering cycle starting with sysinit.target/stop
Sep 14 00:22:06 xxxxxxxx systemd[1]: Stopping firewalld.service - firewalld - dynamic firewall daemon...
```

I saw a few leaving `firewalld` due to this, is it the only solution to not take a risk with service order?

Thank you,

**Comment by mohag** [comment] 2024-09-16 06:42
> I saw a few leaving `firewalld` due to this, is it the only solution to not take a risk with service order?
IIRC, my replacement file is mostly based on the one that Fedora used at the time... The Red Hat family didn't use the upstream unit file either...

**Comment by levi-jcbs** [comment] 2024-09-30 19:30
Can someone please explain to me, why [352aeb5](https://github.com/firewalld/firewalld/commit/352aeb59fcfef2d4395dc4aebec9e0aa2a70631e) was reverted? What's the downside of applying this change manually?

**Comment by erig0** [comment] 2024-10-02 13:00
>Can someone please explain to me, why [352aeb5](https://github.com/firewalld/firewalld/commit/352aeb59fcfef2d4395dc4aebec9e0aa2a70631e) was reverted? What's the downside of applying this change manually?

The answer [is further up in this issue](https://github.com/firewalld/firewalld/issues/414#issuecomment-1144877475). It didn't work for some distros.

**Comment by erig0** [comment] 2024-10-02 13:03
To be clear, if someone proposes a working solution we'll happily merge it. AFAIK, we don't have one.

**Comment by mbiebl** [comment] 2024-10-02 20:48
I don't have an answer either aside from what I said earlier

**Comment by erig0** [comment] 2024-10-03 17:37
Okay. Let me reiterate the problem.

## Problem

1. `cloud-init-local` causes `network-pre` to be started due to `Wants`-ing it.
    
    `cloud-init-local.service`:
    ```
    Before=network-pre.target
    Wants=network-pre.target
    Before=sysinit.target
    ```

2. This forces `firewalld` to start due `Before: network-pre`.
    `firewalld.service`:
    ```
    Before=network-pre.target
    Wants=network-pre.target
    ```

The actual conflict is around `sysinit` and `network-pre`. `cloud-init-local` wants to start _before_ `sysinit`. `firewalld` wants to start _after_ `sysinit`. This can't be done because they both want to start before `network-pre`.

## WORKAROUND

There is no real fix here. I'm only suggesting the following workaround.

Remove these lines from `firewalld.service`:
```
Before=network-pre.target
Wants=network-pre.target
```

## Previous Attempt to fix

Previously there was an attempt to replace firewalld's `network-pre` dependency with `network`, see commit https://github.com/firewalld/firewalld/commit/352aeb59fcfef2d4395dc4aebec9e0aa2a70631e. A user reported that [this didn't work](https://github.com/firewalld/firewalld/issues/414#issuecomment-1144877475) for them.

Perhaps this could be retested by others.

## Further Discussion

- `network-pre` is _meant_ for firewalls. firewalld is correct to be using this.

**Comment by mohag** [comment] 2024-10-04 06:26
Cloud-init's rationale [with that unit is here](https://docs.cloud-init.io/en/24.1/explanation/boot.html#local). (Their [template generating that unit is here](https://github.com/canonical/cloud-init/blob/main/systemd/cloud-init-local.service.tmpl))

It seems that the fundamental issue is that `network-pre.target` and `sysinit.target` are independent and things make different assumptions on how they relate... (and in this case, effectively require conflicting relevant ordering between those targets)

Fedora included a different unit file until Fedora 39. [This is the last version](https://src.fedoraproject.org/rpms/firewalld/blob/f39/f/firewalld.service). I'm not sure how Fedora / RHEL deals with this loop. (I see there is some special cases in the cloud-init-local.service template for those)

It might work to set `DefaultDependencies=no` and explictly depend on stuff needed, e.g. `local-fs.target`, `dbus.socket`? (I'm not sure what is actually needed)? (cloud-init-local also depends on dbus)

**Comment by mbiebl** [comment] 2024-10-07 14:47
@mohag see the discussion earlier, why `DefaultDependencies=no` is not a trivial change: 
https://github.com/firewalld/firewalld/issues/414#issuecomment-1091654448
https://lists.freedesktop.org/archives/systemd-devel/2022-March/047538.html

**Comment by erig0** [comment] 2024-10-07 15:35
I think there are two options:

1. make firewalld an early boot service, e.g. `DefaultDependencies=no`
    - significant code changes to deal with dbus not being available

2. remove `Before=network-pre.target` and `Wants=network-pre.target`
    - major downside is that networking may come up before firewalld

I think we should investigate #1, then if that fails we can fallback to #2.

Agree? Thoughts?

**Comment by mbiebl** [comment] 2024-10-07 15:40
Also keep in mind that firewalld.service has After=polkit.service (which itself is a dbus service).
So if you want to turn firewalld into an early boot service this means (afaics) being able to cope with dbus not being available and polkit not being available (at the very least).

**Comment by mohag** [comment] 2024-10-07 16:37
> @mohag see the discussion earlier, why `DefaultDependencies=no` is not a trivial change: [#414 (comment)](https://github.com/firewalld/firewalld/issues/414#issuecomment-1091654448) https://lists.freedesktop.org/archives/systemd-devel/2022-March/047538.html

Wouldn't a dependency on `dbus.socket` solve that? (That seems to be what cloud-init-local is doing) (I'm not 100% sure when the socket units becomes available) (well, or what happens if the socket is accessed before the dependent service is started? (blocking is my guess))

**Comment by DarkArc** [comment] 2025-08-05 19:30
> Also keep in mind that firewalld.service has After=polkit.service (which itself is a dbus service). So if you want to turn firewalld into an early boot service this means (afaics) being able to cope with dbus not being available and polkit not being available (at the very least).

Can someone familiar with the code comment on how big of a job that might be?

It looks like firewalld depends on dbus during initialization for the bus name which is used to register firewalld with dbus. It looks like the core firewall is already abstracted to be relative dbus free. So presumably, rather than the core firewall startup being part of the firewalld dbus wrapper (which appears to be `firewalld.py`) it could be started directly from `server.py`. firewalld could later be notified (in some way, perhaps a task that sends a signal over a unix domain socket?) that dbus is up and create the dbus service wrapper with the core firewall passed in along with the bus.

Is that even close to accurate? If so, this doesn't seem _that_ unreasonable of a change to make, it would (I think?) primarily be an issue of what the correct mechanism is to notify firewalld to setup its dbus service portion.

**Comment by mbiebl** [comment] 2025-08-05 21:08
Quoting from the discussion on the systemd mailing list
```
In systemd we have some services which do D-Bus and run in early boot,
specifically networkd, resolved and systemd itself. They do that by
simply not doing D-Bus that early, and watching the d-bus socket so
that they connect the moment it becomes available. It's ugly as fuck,
though and very hard to get right, it took us quite some time to get
this reasonably right and race-free.
```

**Comment by DarkArc** [comment] 2025-08-05 22:00
Polling dbus is a bit of an ugly way to do it, particularly if you have other dependencies that need to know when you're dbus ready.

Another way to do it potentially would be two services ... something like `firewalld-core` and `firewalld`. `firewalld` would be a `oneshot` service that depends on dbus and sends a signal to `firewalld-core` to enable the dbus portion. 

That presumably avoids the race conditions they had because things that need `firewalld` w/ dbus can depend on the oneshot service.

**Comment by mbiebl** [comment] 2025-08-06 16:49
> Polling dbus is a bit of an ugly way to do it, particularly if you have other dependencies that need to know when you're dbus ready.

I think they use inotify to monitor the dbus socket.

**Comment by erig0** [comment] 2025-11-22 01:37
Recently, I made changes such that firewalld no longer claims the dbus name until the rules are full loaded. See 63d2238d055ee193f18acb51f6362b64d11e0886.

As such, I think it makes sense to allow firewalld to start before dbus. Then it can just spin trying to connect to dbus. You'll still have a firewall but you won't be able to configure it (actually, firewall-offline-cmd will still work). This means it could start long before dbus and thus be an early boot service.

It will not support dbus restarts though.

I think this is a decent solution here.

**Comment by erig0** [comment] 2025-11-22 02:54
I opened #1528 with some untested code. Please take a look at the systemd service changes.

**Comment by uniuuu** [comment] 2025-11-22 03:08
> Have you had any luck with that workaround, [@uniuuu](https://github.com/uniuuu) ? 🤞


> I'm testing next workaround now:
> 
> ```
> mkdir -p /etc/systemd/system/firewalld.service.d/
> cat > /etc/systemd/system/firewalld.service.d/no-polkit-wait.conf << 'EOF'
> [Unit]
> After=dbus.service
> After=
> After=dbus.service network-pre.target
> EOF
> 
> systemctl daemon-reload
> reboot
> ```

Yes, it works 🎉. 
I don't see in my particular setup any impact from this workaround. My server is meant only for docker and firewalld and the cloud-init is coming from my hosting provider's image. 

I cannot say the same for any other possible scenario when you have some **other** packages in the chain or your poolkit hasn't started due to some specific configuration.  If poolkit is not started (or yet not started - imagine it will start just too late for your specific configuration) then any modification to firewall configuration via firewall-cmd or D-Bus will started. 

Right answer: it works, but you've been warned !




> Recently, I made changes such that firewalld no longer claims the dbus name until the rules are fully loaded. See [63d2238](https://github.com/firewalld/firewalld/commit/63d2238d055ee193f18acb51f6362b64d11e0886).
> 
> As such, I think it makes sense to allow firewalld to start before dbus. Then it can just spin trying to connect to dbus. You'll still have a firewall but you won't be able to configure it (actually, firewall-offline-cmd will still work *). This means it could start long before dbus and thus be an early boot service.
> 
> It will not support dbus restarts though.
> 
> I think this is a decent solution here. I'll try to prioritize this.
> 
> [*]: There is some sort of "file watcher" code that is suppose to scan and update when config changes, but I've barely touched that code. Thus, I expect new features have poor test coverage there. :D

@erig0 Thank you!

**Comment by erig0** [comment] 2025-11-22 03:11
/me vanishes into a cloud of PTO. ☁️

**Comment by erig0** [comment] 2025-12-02 11:55
Bump. Can we get more eyes/test on #1528? I'd like to merged it since this is impacting the community so much.

Thanks @mohag!
