### ISSUE TITLE
tftp-client service does not put helper rule in filter_OUTPUT chain

### ISSUE THREAD

**Issue by space88man** [firewalld/firewalld#600] opened 2020-04-03 15:34 UTC
Revisiting #185 but now in  the context of nftables. What is the status of OUTPUT support?

Attempting to enable tftp client:
```
# I want to make outbound tftp requests to a TFTP server
firewall-cmd --add-service tftp-client
```
The rule `udp dport 69 ct helper set "helper-tftp-udp" # handle 497`goes into the wrong chain:

```
        chain filter_IN_FedoraWorkstation_allow { # handle 272
                ip6 daddr fe80::/64 udp dport 546 ct state { new, untracked } accept # handle 280
                tcp dport 22 ct state { new, untracked } accept # handle 282
                udp dport 69 ct helper set "helper-tftp-udp" # handle 497
        }
```
As a result TFTP-as-client connections fail.

As the old issue mentions, the rule belongs to an  OUTPUT chain? E.g.,

```
# with this rule, TFTP-as-client works.
nft add rule inet firewalld filter_OUTPUT udp dport 69 ct helper set  helper-tftp-udp
```

**Comment by erig0** [comment] 2020-04-03 15:57
Duplicate of #185.

**Comment by erig0** [comment] 2020-04-03 15:58
For status of OUTPUT filtering see this card: https://github.com/orgs/firewalld/projects/1#card-25963208

**Closed by erig0** 2020-04-03 15:57 UTC
Labels: duplicate
