### ISSUE TITLE
[feature] Zone to zone chains for forward rules

### ISSUE THREAD

**Issue by gasinvein** [firewalld/firewalld#309] opened 2018-03-07 16:44 UTC
I think it will be useful if FirewallD would create "from zone X to zone Y" chains for active zones, which would handle packages forwarded coming from one zone to another. 
For example, packages to be forwarded from an interface (or source address) in `internal` zone to interface in `external` zone go to chain `FWD_internal_to_external` . It would make adding FORWARD rules much easier, thus making FirewallD more useful for a router.

**Comment by erig0** [comment] 2019-05-31 14:01
This is a duplicate of #2.

**Closed by erig0** 2019-05-31 14:01 UTC
Labels: duplicate, enhancement
