### ISSUE TITLE
ipset list:set feature

### ISSUE THREAD

**Issue by nickdsl** [firewalld/firewalld#365] opened 2018-08-06 16:02 UTC
Hello!
Why firewalld doesn't support ipset list:set type?

**Comment by erig0** [comment] 2018-08-07 15:30
Because no on has implemented it.

**Comment by erig0** [comment] 2018-08-08 17:12
Dupe of #324.

**Closed by erig0** 2018-08-08 17:12 UTC
Labels: duplicate, enhancement

**Comment by fuleru** [comment] 2024-07-17 01:38
Yes, can firewalld support ipset list:set type?

```
#ipset help | grep support$ | awk -F " " '{print $1}' | sort -u
bitmap:ip
bitmap:ip,mac
bitmap:port
hash:ip
hash:ip,mark
hash:ip,port
hash:ip,port,ip
hash:ip,port,net
hash:net
hash:net,iface
hash:net,net
hash:net,port
hash:net,port,net
list:set


# firewall-cmd --get-ipset-types
hash:ip hash:ip,mark hash:ip,port hash:ip,port,ip hash:ip,port,net hash:mac hash:net hash:net,iface hash:net,net hash:net,port hash:net,port,net

```
