### ISSUE TITLE
public.xml not restricting by source address

### ISSUE THREAD

**Issue by johnsinsf** [firewalld/firewalld#1359] opened 2024-06-27 15:44 UTC
### What happened

One zone file, "public.xml", with one port and one source address. Looking at the zones with --get-all-zones it looked correct but the server was wide open. I double-checked everything, restarted, it still would not restrict access. I changed the name of the zone file to "external.xml" and it works. --get-all-zones looks the same, except for the name change.

### What you expected to happen

The docs say public.xml should restrict the ports. firewall-config GUI also showed everything configured, but it didn't block access from the internet.

### How to reproduce it (as minimally and precisely as possible)

/etc/firewalld/zones/public.xml does not work, leaves server open:

<?xml version="1.0" encoding="utf-8"?>
<zone>
  <short>Public</short>
  <description>test</description>
  <source address="1.1.1.1/32"/>
  <port port="2000" protocol="tcp"/>
</zone>

rename to /etc/firewalld/zones/external.xml and restart firewalld does work:

<?xml version="1.0" encoding="utf-8"?>
<zone>
  <short>External</short>
  <description>test</description>
  <source address="1.1.1.1/32"/>
  <port port="2000" protocol="tcp"/>
</zone>

### Firewalld Version

0.6.3

### Linux distribution

centos 7

### Linux kernel version

3.10.0-1160.118.1.el7.x86_64

**Comment by erig0** [comment] 2024-07-01 17:27
This sounds like a misconfiguration. Can you show `firewall-cmd --get-default-zone` ?

Also check the log file, `/var/log/firewalld`, for any recent errors. It's possible the service  is not starting correctly.

**Comment by johnsinsf** [comment] 2024-07-02 10:51
I know it sounds like it must be configuration, but it seemed important so I reported it anyway :) 

I took the config from a previously working system and it’s so simple. I’ll certainly do another test to see what it was.

Here’s what was configured at the time, if you notice anything wrong, let me know!

***@***.*** log]# firewall-cmd --get-active-zones
public
  interfaces: em2
  sources: 192.168.123.0/24 10.0.0.0/16 173.8.xxx.x
***@***.*** log]# 

***@***.*** zones]# firewall-cmd --list-all-zones
block
  target: %%REJECT%%
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

dmz
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

drop
  target: DROP
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

external
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: ssh
  ports: 
  protocols: 
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

home
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

internal
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

public (active)
  target: default
  icmp-block-inversion: no
  interfaces: em2
  sources: 192.168.123.0/24 10.0.0.0/16 173.8.xxx.x
  services: 
  ports: xxxx/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

trusted
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

work
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules:

**Comment by erig0** [comment] 2024-07-02 18:31
I'm not sure what you mean by "wide open". I see you added sources to the `public` zone. If by "wide open" you mean others sources are allowed to access the server, e.g. ssh then it's probably because `public` is also the default zone.

The default zone, `public` by default, is the zone that all unassigned traffic goes to.
You can check this with

```
# firewall-cmd --get-default-zone
```

You can change the default zone to something much more restrictive, e.g. `drop`.
```
# firewall-cmd --set-default-zone drop
```

**Comment by johnsinsf** [comment] 2024-07-08 14:55
Hi!

I couldn’t make any changes to the original system, it’s too far away, so I tried this on my test system. This is on Centos 3.10.0-1160.88.1.el7.x86_64.

I don’t use port 22 and I’m aware the public zone allows that by default. I can’t connect on that port and sshd not running on that port.

But using the configuration below I can connect from address 192.168.122.27 to port 12000 when it should be blocked:

 07:25:57 up 178 days, 19:55,  2 users,  load average: 0.27, 0.27, 0.31
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
johns    pts/2    10.0.2.204       07:16    9:01   0.07s  0.07s -bash
johns    pts/14   192.168.122.27   07:17    5.00s  0.24s  0.19s sshd: johns [priv]  


Here’s the output for the zones, I have two active zones and only port 12000 should be allowed from the source addresses listed, correct?

***@***.*** log]# firewall-cmd --list-all-zones
block
  target: %%REJECT%%
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

dmz
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

drop
  target: DROP
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

external (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 10.0.0.0/16
  services: 
  ports: 12000/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

home
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

internal
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

public (active)
  target: default
  icmp-block-inversion: no
  interfaces: em1 em2 em3 team0
  sources: 192.168.123.0/24 173.8.141.1/32
  services: 
  ports: 12000/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

trusted
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	

work
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 


The firewalld log has this entry, not sure why, I don’t use port 67 on that system:

2024-07-03 09:31:38 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -w --table filter --delete INPUT --in-interface virbr0 --protocol tcp --destination-port 67 --jump ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

In looking at the output from iptables, could it be the FORWARD policy? I’m not setting that myself, it’s the only reference I see but then there’s this as well which looks like it’s open:

Chain IN_public_allow (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:entextxid ctstate NEW,UNTRACKED


***@***.*** firewalld]# iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
INPUT_direct  all  --  anywhere             anywhere            
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere            
INPUT_ZONES  all  --  anywhere             anywhere            
LOG        all  --  anywhere             anywhere             ctstate INVALID LOG level warning prefix "STATE_INVALID_DROP: "
DROP       all  --  anywhere             anywhere             ctstate INVALID
LOG        all  --  anywhere             anywhere             LOG level warning prefix "FINAL_REJECT: "
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             192.168.122.0/24     ctstate RELATED,ESTABLISHED
ACCEPT     all  --  192.168.122.0/24     anywhere            
ACCEPT     all  --  anywhere             anywhere            
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
FORWARD_direct  all  --  anywhere             anywhere            
FORWARD_IN_ZONES_SOURCE  all  --  anywhere             anywhere            
FORWARD_IN_ZONES  all  --  anywhere             anywhere            
FORWARD_OUT_ZONES_SOURCE  all  --  anywhere             anywhere            
FORWARD_OUT_ZONES  all  --  anywhere             anywhere            
LOG        all  --  anywhere             anywhere             ctstate INVALID LOG level warning prefix "STATE_INVALID_DROP: "
DROP       all  --  anywhere             anywhere             ctstate INVALID
LOG        all  --  anywhere             anywhere             LOG level warning prefix "FINAL_REJECT: "
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootpc
ACCEPT     all  --  anywhere             anywhere            
OUTPUT_direct  all  --  anywhere             anywhere            

Chain FORWARD_IN_ZONES (1 references)
target     prot opt source               destination         
FWDI_public  all  --  anywhere             anywhere            [goto] 
FWDI_public  all  --  anywhere             anywhere            [goto] 
FWDI_public  all  --  anywhere             anywhere            [goto] 
FWDI_public  all  --  anywhere             anywhere            [goto] 
FWDI_public  all  --  anywhere             anywhere            [goto] 

Chain FORWARD_IN_ZONES_SOURCE (1 references)
target     prot opt source               destination         
FWDI_external  all  --  10.0.0.0/16          anywhere            [goto] 
FWDI_public  all  --  192.168.123.0/24     anywhere            [goto] 
FWDI_public  all  --  173-8-141-1-SFBA.hfc.comcastbusiness.net  anywhere            [goto] 

Chain FORWARD_OUT_ZONES (1 references)
target     prot opt source               destination         
FWDO_public  all  --  anywhere             anywhere            [goto] 
FWDO_public  all  --  anywhere             anywhere            [goto] 
FWDO_public  all  --  anywhere             anywhere            [goto] 
FWDO_public  all  --  anywhere             anywhere            [goto] 
FWDO_public  all  --  anywhere             anywhere            [goto] 

Chain FORWARD_OUT_ZONES_SOURCE (1 references)
target     prot opt source               destination         
FWDO_external  all  --  anywhere             10.0.0.0/16         [goto] 
FWDO_public  all  --  anywhere             192.168.123.0/24    [goto] 
FWDO_public  all  --  anywhere             173-8-141-1-SFBA.hfc.comcastbusiness.net [goto] 

Chain FORWARD_direct (1 references)
target     prot opt source               destination         

Chain FWDI_external (1 references)
target     prot opt source               destination         
FWDI_external_log  all  --  anywhere             anywhere            
FWDI_external_deny  all  --  anywhere             anywhere            
FWDI_external_allow  all  --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere            

Chain FWDI_external_allow (1 references)
target     prot opt source               destination         

Chain FWDI_external_deny (1 references)
target     prot opt source               destination         

Chain FWDI_external_log (1 references)
target     prot opt source               destination         

Chain FWDI_public (7 references)
target     prot opt source               destination         
FWDI_public_log  all  --  anywhere             anywhere            
FWDI_public_deny  all  --  anywhere             anywhere            
FWDI_public_allow  all  --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere            

Chain FWDI_public_allow (1 references)
target     prot opt source               destination         

Chain FWDI_public_deny (1 references)
target     prot opt source               destination         

Chain FWDI_public_log (1 references)
target     prot opt source               destination         

Chain FWDO_external (1 references)
target     prot opt source               destination         
FWDO_external_log  all  --  anywhere             anywhere            
FWDO_external_deny  all  --  anywhere             anywhere            
FWDO_external_allow  all  --  anywhere             anywhere            

Chain FWDO_external_allow (1 references)
target     prot opt source               destination         

Chain FWDO_external_deny (1 references)
target     prot opt source               destination         

Chain FWDO_external_log (1 references)
target     prot opt source               destination         

Chain FWDO_public (7 references)
target     prot opt source               destination         
FWDO_public_log  all  --  anywhere             anywhere            
FWDO_public_deny  all  --  anywhere             anywhere            
FWDO_public_allow  all  --  anywhere             anywhere            

Chain FWDO_public_allow (1 references)
target     prot opt source               destination         

Chain FWDO_public_deny (1 references)
target     prot opt source               destination         

Chain FWDO_public_log (1 references)
target     prot opt source               destination         

Chain INPUT_ZONES (1 references)
target     prot opt source               destination         
IN_public  all  --  anywhere             anywhere            [goto] 
IN_public  all  --  anywhere             anywhere            [goto] 
IN_public  all  --  anywhere             anywhere            [goto] 
IN_public  all  --  anywhere             anywhere            [goto] 
IN_public  all  --  anywhere             anywhere            [goto] 

Chain INPUT_ZONES_SOURCE (1 references)
target     prot opt source               destination         
IN_external  all  --  10.0.0.0/16          anywhere            [goto] 
IN_public  all  --  192.168.123.0/24     anywhere            [goto] 
IN_public  all  --  173-8-141-1-SFBA.hfc.comcastbusiness.net  anywhere            [goto] 

Chain INPUT_direct (1 references)
target     prot opt source               destination         

Chain IN_external (1 references)
target     prot opt source               destination         
IN_external_log  all  --  anywhere             anywhere            
IN_external_deny  all  --  anywhere             anywhere            
IN_external_allow  all  --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere            

Chain IN_external_allow (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:entextxid ctstate NEW,UNTRACKED

Chain IN_external_deny (1 references)
target     prot opt source               destination         

Chain IN_external_log (1 references)
target     prot opt source               destination         

Chain IN_public (7 references)
target     prot opt source               destination         
IN_public_log  all  --  anywhere             anywhere            
IN_public_deny  all  --  anywhere             anywhere            
IN_public_allow  all  --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere            

Chain IN_public_allow (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:entextxid ctstate NEW,UNTRACKED

Chain IN_public_deny (1 references)
target     prot opt source               destination         

Chain IN_public_log (1 references)
target     prot opt source               destination         

Chain OUTPUT_direct (1 references)
target     prot opt source               destination         

Thanks for any help!

—johnS

**Comment by johnsinsf** [comment] 2024-09-10 23:49
Thanks! So you’re saying the Public Zone does not restrict by source address, correct?

—johnS

**Comment by johnsinsf** [comment] 2024-09-11 15:55
Thanks for clearing that up!

So you’re saying my original public.xml zone file:

<?xml version="1.0" encoding="utf-8"?>
<zone>
  <short>Public</short>
  <description>For use in public areas. You do not trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.</description>
  <port port="12000" protocol="tcp"/>
  <source address="10.0.0.0/16"/>
</zone>

had valid syntax, but it won’t restrict anything without also typing:

#firewall-cmd --set-default-zone block

Do I have that correct? And then it will restrict by source address?

Thanks again, I just want to make sure I have this right!

—johnS

**Comment by erig0** [comment] 2024-09-11 16:11
Yes. That's correct.

**Comment by erig0** [comment] 2024-09-13 13:26
Closing as not a bug.

**Closed by erig0** 2024-09-13 13:26 UTC
Labels: not a bug
