### ISSUE TITLE
Some conntrack helpers belong on OUTPUT, not PREROUTING

### ISSUE THREAD

**Issue by henryptung** [firewalld/firewalld#452] opened 2019-01-16 12:35 UTC
It seems like helpers are being attached to the prerouting hook, but based on examples, helpers like netbios-ns need to be attached to the output hook since they detect outgoing broadcasts and set up expectations for reply packets:

https://www.google.com/search?q=%22j+CT%22+helper+netbios-ns

If there's no way to configure helpers to attach to raw_OUTPUT rather than raw_POSTROUTING, this seems like a fundamental gap in firewalld handling and a misconfiguration of the `netbios-ns` and `snmp` helpers in firewalld, at a minimum.

**Comment by henryptung** [comment] 2019-01-16 12:59
Based on #185, seems like TFTP falls in the same bucket.

**Comment by erig0** [comment] 2019-02-19 16:55
@henryptung, correct. firewalld lacks real OUTPUT filtering. This is a prerequisite to true client helpers.

**Comment by erig0** [comment] 2019-02-19 17:00
Close as a duplicate of #185. I'll modify that issue to further describe the issue.

**Closed by erig0** 2019-02-19 17:00 UTC
