### ISSUE TITLE
Does firewalld still not work with virtual-IP addresses?

### ISSUE THREAD

**Issue by RichardSharpe** [firewalld/firewalld#245] opened 2017-09-18 01:19 UTC
I am working with firewalld-0.4.3.2-8.1.el7_3.noarch ...

When I try this:
```IP63 ~ $ ifconfig
ens160: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.29.11.183  netmask 255.255.255.0  broadcast 172.29.11.255
        inet6 fe80::250:56ff:fe8c:fa71  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:8c:fa:71  txqueuelen 1000  (Ethernet)
        RX packets 350057  bytes 86486273 (82.4 MiB)
        RX errors 2  dropped 2  overruns 0  frame 0
        TX packets 288270  bytes 32124143 (30.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens160:0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.29.11.106  netmask 255.255.255.0  broadcast 172.29.11.255
        ether 00:50:56:8c:fa:71  txqueuelen 1000  (Ethernet)
...
IP63 ~ $ firewall-cmd --get-active-zones
public
  interfaces: ens160 ens161 ens192
IP63 ~ $ firewall-cmd --zone=public --add-interface=ens160:0
success
IP63 ~ $ firewall-cmd --get-active-zones
public
  interfaces: ens160 ens161 ens192 ens160:0
IP63 ~ $ firewall-cmd --remove-rich-rule 'rule family="ipv4" destination address="172.29.11.106" forward-port to-addr="192.168.122.10" to-port="22" protocol="tcp" port="22"'
Warning: NOT_ENABLED: 'rule family="ipv4" destination address="172.29.11.106" forward-port port="22" protocol="tcp" to-port="22" to-addr="192.168.122.10"' not in 'public'
```

I get that error shown. Has it been fixed or is it planned to be fixed or do I have to move to iptables?

**Comment by erig0** [comment] 2017-10-13 20:13
I'm not sure what you're reporting here. It looks like you're trying to remove a rich rule that does not exist. What does `firewall-cmd --list-rich-rules` show?

**Comment by RichardSharpe** [comment] 2017-10-14 01:14
Looks like in my haste I copied the incorrect command.

I was trying to add a rich rule that referred to a virtual IP address and it failed.

I will have to go back and set it up again to see if I can repro it.

**Comment by erig0** [comment] 2018-01-19 19:04
@RichardSharpe, Any luck reproducing? If not I will close.

**Comment by erig0** [comment] 2018-02-12 22:15
Closing as per my previous comment.

**Closed by erig0** 2018-02-12 22:15 UTC
Labels: insufficient data
