### ISSUE TITLE
forward from one zone to another with something other than direct rules?

### ISSUE THREAD

**Issue by brianjmurrell** [firewalld/firewalld#545] opened 2019-11-24 02:35 UTC
This may be a duplicate of #2 but I thought I would open a new ticket just in case it's not.

If I have a machine running firewalld that looks like:

```
                      -----------
--------internal------|firewalld|--------vpn----
                      -----------
```

and I want to allow a given source (mac in my case, but it could be IP address) in zone _internal_ to send packets to a given destination in zone _vpn_.  Is a **direct** rule the only choice here?

If so, I'm really not quite sure I see the point of **firewalld** for this kind of machine over just writing an `/etc/rc.d/rc.local` script with a few 10s/dozens/hundreds of `iptables` commands.  Or using a firewalling package that truly understands routing like [Shorewall](http://shorewall.org/).  But I just wanted to confirm my understanding of **firewalld** before ditching **firewalld* for something like **Shorewall**.

**Comment by brianjmurrell** [comment] 2019-11-24 02:40
I suppose what confuses me the most about this is that if _direct_ rules really are the only way to forward from one zone to another, what are all of the `FORWARD_*`, `FWDI_*`, and `FWDO_*` _iptables_ rules all about?

**Comment by erig0** [comment] 2019-11-25 13:55
- `FORWARD_*` is an intermediate to `FWDI_*` and `FWDO_*`
- `FWDI_*` is used by --add-icmp-block
- `FWDO_*` is used by --add-masquerade to allow existing connections, but after looking I think this is redundant as there is a generic "accept existing connections" at the start of the FORWARD chain.

`FWDI_*` and `FWDO_*` also enforce the `--set-target` for the zone. i.e. if `--set-target=drop`, then there will be a catch-all `drop` at the end of both chains.

**Comment by erig0** [comment] 2019-11-25 13:56
Marking as duplicate of #2.

**Closed by erig0** 2019-11-25 13:56 UTC

**Comment by erig0** [comment] 2019-11-25 14:00
> If so, I'm really not quite sure I see the point of **firewalld** for this kind of machine over just writing an `/etc/rc.d/rc.local` script with a few 10s/dozens/hundreds of `iptables` commands. Or using a firewalling package that truly understands routing like [Shorewall](http://shorewall.org/). But I just wanted to confirm my understanding of **firewalld** before ditching *_firewalld_ for something like **Shorewall**.

Support for forward and output filtering is [in progress](https://github.com/orgs/firewalld/projects/1#card-25963208). I hope to see it in the next feature release.
