### ISSUE TITLE
Firewalld Not rejecting IP's

### ISSUE THREAD

**Issue by Wilburunion** [firewalld/firewalld#617] opened 2020-04-25 19:32 UTC
My VPS provider upgraded the Kernel to 3.10 and now port scans are hammering the machine.  The worst of them I created a rich text rule to reject it.  The IP is still coming through. triggering PSAD and filling both the log and my mail inbox.  The provider says they changed the kernel-firewall so it can only accept 200 rules - down from the 10,000 it once was.  I had never heard of such a thing and I question the wisdom of that - as they are trying to save CPU time checking firewall rules on shared CPU's.  Is this a real thing - and is it wise - as it looks like the firewall dies not work at all any more - and I had to do a "iptables-restore" manually before  to get the iptables to reload on restart.  firewalld keeps crashing now - dying.

1.  Is there such a way to limit the rules to 200 - and is it advisable standard practice for a VPS or have they just screwed things up with such a limit - AND 

2.  It appears enabling the following filters detect and/or block port scans and host sweeps.

7000: TCP: Port Scan
7001: UDP: Port Scan
7002: TCP: Host Sweep
7003: UDP: Host Sweep
7004: ICMP: Host Sweep
7016: ICMPv6: Host Sweep

should solve some of the problem - but I cannot find an example of how to enable this using iptables or a direct.xml entry

can anyone give me the syntax ??

This info is from https://success.trendmicro.com/solution/TP000087920-How-do-I-block-NMAP-port-scans

**Comment by erig0** [comment] 2020-04-27 12:31
Do you have a full VPS (e.g. KVM, OpenStack) or a container technology, e.g. OpenVZ?

> firewalld keeps crashing now - dying.

Is firewalld dying because applying rules fails?

>     1. Is there such a way to limit the rules to 200 - and is it advisable standard practice for a VPS or have they just screwed things up with such a limit - AND

No.

>     2. It appears enabling the following filters detect and/or block port scans and host sweeps.
> 
> 
> 7000: TCP: Port Scan
> 7001: UDP: Port Scan
> 7002: TCP: Host Sweep
> 7003: UDP: Host Sweep
> 7004: ICMP: Host Sweep
> 7016: ICMPv6: Host Sweep

firewalld blocks these by default. You shouldn't have to do anything extra.

**Comment by Wilburunion** [comment] 2020-04-27 15:23
Hi thanks for responding

It is an OpenVZ 7 (3.10 kernel) container NOW  - recently upgraded from OpenVZ 6 (from a 2.6.32 kernel ) on April 23, 2020 when the system went crazy with port scans coming and being alerted by email by PSAD and I saw fail2ban no longer running

Product | Release date | EOL | Status | Release notes | Kernel branch
-- | -- | -- | -- | -- | --
OpenVZ 7 | 25 Jul 2016 | TBD | Supported | Readme | RHEL7 (3.10)
OpenVZ-legacy (RHEL6 based) | 14 Oct 2011 | Nov 2019 | Supported | NA | RHEL6 (2.6.32)

They upgraded obviously because it was end of life for OpenVZ 6 in Nov 2019  See https://wiki.openvz.org/Releases

ipset and nf_conntrack did not work on the 2.6.32 kernel and they claim it will on this 3.10 kernel, but firewalld seems to be hacked to me.

I know  the problem is that it's an OpenVZ VPS. which  are not actually virtual machines, but containers. On these one is at the mercy of the kernel modules through only the grace of the intervention of the hosting provider. --- but it is not working like it used to - port scans and IP's are not being blocked - and if you say there is no way to limit rules by number what are they doing??

One IP in particular was slamming  scans continuously and so I put in a rich text rule to reject the IP -but it kept coming through it appeared another with an ip6 notation was the same

When I opened a trouble ticket they revealed the new system - which they did not even tell me was happening - which I saw must have happened because the kernel had changed from version 2 to 3.10 - that the new migration only allowed for 200 rules - capped - down from the previous 10,000 limit.  I told them my rich text reject rules were well over that alone.  The firewalld kept dying.  then they claimed my container actually had a 2000 rule limit.  iptables-restore had not worked - and I had to launch it manually

I then discovered fail2ban was not running and when I launched it and it made its entries into the icmp reject list it went well over 2000 rules and then the firewalld  - basically locked up and reported "memory allocation problem" when trying to add an iptable rule of any kind.

It appeared that PSAD was still not  working  as the email alerts kept coming - but I can not be sure but they may have been backed up in a Postfix queue of 20,000 backed up email alerts due the persistent port scanning and PSAD's inability to block IP's to stop the scans.

I then did a firewalld--cmd --reload with a  smaller public.xml file that allowed me to use the following filter inputs to try to stop the port scans since I could find nothing on the filter 7000 to 7004 and 7016 and the hosting company did not even know what I was asking about with these filter numbers - - in fact they did not even know what a rich-text rule  was nor what direct.xml was.

the rules I tried was 

iptables -A INPUT -p tcp --tcp-flags SYN,ACK SYN,ACK -m state --state NEW -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP

iptables -A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
iptables -A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP

iptables -A INPUT -p tcp --tcp-flags FIN,RST FIN,RST -j DROP
iptables -A INPUT -p tcp --tcp-flags ACK,FIN FIN -j DROP
iptables -A INPUT -p tcp --tcp-flags ACK,PSH PSH -j DROP
iptables -A INPUT -p tcp --tcp-flags ACK,URG URG -j DROP

which showed up in the tables like this before save

10 DROP tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x12/0x12 state NEW
11 DROP tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x3F/0x00
12 DROP tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x03/0x03
13 DROP tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x06/0x06
14 DROP tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x3F/0x37
15 DROP tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x05/0x05
16 DROP tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x11/0x01
17 DROP tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x18/0x08
18 DROP tcp -- 0.0.0.0/0 0.0.0.0/0 tcp flags:0x30/0x20

using iptables-save look like this

-A INPUT -p tcp -m tcp --tcp-flags SYN,ACK SYN,ACK -m state --state NEW -j DROP
-A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG NONE -j DROP
-A INPUT -p tcp -m tcp --tcp-flags FIN,SYN FIN,SYN -j DROP
-A INPUT -p tcp -m tcp --tcp-flags SYN,RST SYN,RST -j DROP
-A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG FIN,SYN,RST,ACK,URG -j DROP
-A INPUT -p tcp -m tcp --tcp-flags FIN,RST FIN,RST -j DROP
-A INPUT -p tcp -m tcp --tcp-flags FIN,ACK FIN -j DROP
-A INPUT -p tcp -m tcp --tcp-flags PSH,ACK PSH -j DROP
-A INPUT -p tcp -m tcp --tcp-flags ACK,URG URG -j DROP

which in the /etc/firewalld/direct.xml file I built to look like this

<?xml version="1.0" encoding="utf-8"?>
<direct>
<rule priority="0" table="filter" ipv="ipv4" chain="INPUT_direct">-p tcp --dport 80 -m state --state NEW -m recent --set</rule>
<rule priority="0" table="filter" ipv="ipv4" chain="INPUT_direct">-p tcp -m tcp --tcp-flags SYN,ACK SYN,ACK -m state --state NEW -j DROP</rule>
<rule priority="0" table="filter" ipv="ipv4" chain="INPUT_direct">-p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG NONE -j DROP</rule>
<rule priority="0" table="filter" ipv="ipv4" chain="INPUT_direct">-p tcp -m tcp --tcp-flags FIN,SYN FIN,SYN -j DROP</rule>
<rule priority="0" table="filter" ipv="ipv4" chain="INPUT_direct">-p tcp -m tcp --tcp-flags SYN,RST SYN,RST -j DROP</rule>
<rule priority="0" table="filter" ipv="ipv4" chain="INPUT_direct">-p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG FIN,SYN,RST,ACK,URG -j DROP</rule>
<rule priority="0" table="filter" ipv="ipv4" chain="INPUT_direct">-p tcp -m tcp --tcp-flags FIN,RST FIN,RST -j DROP</rule>
<rule priority="0" table="filter" ipv="ipv4" chain="INPUT_direct">-p tcp -m tcp --tcp-flags FIN,ACK FIN -j DROP</rule>
<rule priority="0" table="filter" ipv="ipv4" chain="INPUT_direct">-p tcp -m tcp --tcp-flags PSH,ACK PSH -j DROP</rule>
<rule priority="0" table="filter" ipv="ipv4" chain="INPUT_direct">-p tcp -m tcp --tcp-flags ACK,URG URG -j DROP</rule>
</direct>

which did load fine on reload 

So now my fail2ban will not work - because it cannot permanently ban IP's anymore  as it goes over the 2000 rule limit  they have somehow set (they won't answer how" - and I am left needing to switch to they ipset-fail2ban project here on github=> https://github.com/ritsu/ipset-fail2ban

Their other solution is to upgrade my account to a solution four times more costly per month in a full VPS (e.g. KVM, OpenStack)

I do not think my firewalld configuration was upgraded - and modprobe nf_conntrack says:

[root@main ~]# modprobe nf_conntrack
modprobe: ERROR: could not find module by name='nf_conntrack'
modprobe: ERROR: could not insert 'nf_conntrack': Function not implemented
modprobe: ERROR: Error running install command for nf_conntrack
modprobe: ERROR: could not insert 'nf_conntrack': Operation not permitted

I have not tried to configure ipset yet

It looks like this is a way to raise the price by making the system closer to useless to push one to a KVM type system

If the firewalld is supposed to do the filtrers above - how would I be able to tell in the config - what are and where are the tell-tale filters or iptables

**Comment by erig0** [comment] 2020-04-27 18:49
>  and if you say there is no way to limit rules by number what are they doing??

I meant there is no way in firewalld. I'm not aware of how to do this in the kernel or host.


> [root@main ~]# modprobe nf_conntrack
> modprobe: ERROR: could not find module by name='nf_conntrack'
> modprobe: ERROR: could not insert 'nf_conntrack': Function not implemented
> modprobe: ERROR: Error running install command for nf_conntrack
> modprobe: ERROR: could not insert 'nf_conntrack': Operation not permitted

This was fixed in 88e76ddfed6fe348975bfea9002da0e4627c6e25. See also #430 and #519.

> If the firewalld is supposed to do the filtrers above - how would I be able to tell in the config - what are and where are the tell-tale filters or iptables

Firewalld is failing to start properly... hence the lack of filtering.

**Comment by erig0** [comment] 2020-04-27 18:51
Marking as a duplicate of #519.

**Closed by erig0** 2020-04-27 18:51 UTC
Labels: question

**Comment by Wilburunion** [comment] 2020-04-27 19:24
They say nf_conntrack is already loaded

# lsmod | grep nf_conntrack
nf_conntrack_ipv6 4242 -2
nf_defrag_ipv6 4242 -2 nf_conntrack_ipv6
nf_conntrack_ftp 4242 -2
nf_conntrack_ipv4 4242 -2
nf_defrag_ipv4 4242 -2 nf_conntrack_ipv4
nf_conntrack 4242 -2 xt_helper,nf_nat,xt_state,xt_
connlimit,nf_nat_ipv4,nf_nat_ipv6,xt_conntrack,nf_nat_
masquerade_ipv4,nf_conntrack_ftp,nf_conntrack_ipv4,nf_conntrack_ipv6
libcrc32c 4242 -2 bnx2x,nf_nat,nf_conntrack

**Comment by erig0** [comment] 2020-04-27 20:05
> They say nf_conntrack is already loaded

Right. But firewalld will attempt to load it. Recently the failure to load modules was made non-fatal. Specifically for use cases like this (OpenVZ, containers).

**Comment by Wilburunion** [comment] 2020-04-27 21:54
So are you saying that with make firewalld not load properly and skip all
the modules and / or needing conn track support??

**Comment by erig0** [comment] 2020-04-28 12:37
On Mon, Apr 27, 2020 at 02:54:23PM -0700, Wilburunion wrote:
> So are you saying that with make firewalld not load properly and skip all
> the modules and / or needing conn track support??

Right. It's fatal. Before the above fix firewalld would exit.

**Comment by Wilburunion** [comment] 2020-04-28 13:56
OK last question.  If I build a stateful firewall calling to the already
lalledgedly loaded conntrack modules using iptables and cmstate calls will
the running firewalld work then with the manual setup like "how to"
illustrated at https://wiki.parabola.nu/Simple_stateful_firewall.??

I told them that firewall was obviously not working after the Openvz 7
upgrade even before I filed this issue

**Comment by erig0** [comment] 2020-04-28 16:48
On Tue, Apr 28, 2020 at 06:56:53AM -0700, Wilburunion wrote:
> OK last question.  If I build a stateful firewall calling to the already
> lalledgedly loaded conntrack modules using iptables and cmstate calls will
> the running firewalld work then with the manual setup like "how to"
> illustrated at https://wiki.parabola.nu/Simple_stateful_firewall.??

No. firewalld won't work at all due to the nf_conntrack issue.

> I told them that firewall was obviously not working after the Openvz 7
> upgrade even before I filed this issue
>
