### ISSUE TITLE
No way to add rule before conntrack RELATED,ESTABLISHED rule

### ISSUE THREAD

**Issue by JellyKid** [firewalld/firewalld#191] opened 2017-01-04 18:49 UTC
With iptables I can 
`iptables -I INPUT -m set --match-set ipset_test src -j DROP`
and it will add the rule to the top of the filter table before the conntrack rule

If I use the firewall-cmd equivalent
`firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -m set --match-set ipset_test src -j DROP`
It adds the rule into the INPUT_direct chain which comes after the conntrack rule
`-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT`

This is a problem for people using ipsets that change dynamically.
For example, fail2ban tracks log entries for a match of some kind and then adds found IPs into an ipset. If the IP exists in the log then a connection has already been established and will not be dropped according the to the way firewalld arranges rules/chains.

I think the easiest thing would be to have a firewalld option that allows INPUT_ZONES* to come before the conntrack rule. To me it makes more sense for the DROP zone to be before the the conntrack rule so that even if a connection is established if the source exists in the DROP zone traffic will be filtered accordingly.

**Comment by marcosfrm** [comment] 2017-02-12 09:39
> For example, fail2ban tracks log entries for a match of some kind and then adds found IPs into an ipset. If the IP exists in the log then a connection has already been established and will not be dropped according the to the way firewalld arranges rules/chains.

Got bitten by this today.

fail2ban 0.9.x (version in EPEL 7) firewallcmd-ipset action:

https://github.com/fail2ban/fail2ban/blob/0.9/config/action.d/firewallcmd-ipset.conf

**Comment by marcosfrm** [comment] 2017-02-12 10:25
Probably duplicate of #44 .

**Comment by erig0** [comment] 2017-10-13 20:01
Closing as duplicate of #44.

**Closed by erig0** 2017-10-13 20:01 UTC
Labels: duplicate
