### ISSUE TITLE
Firewalld Config 1.1.1 Error

### ISSUE THREAD

**Issue by gh4wi** [firewalld/firewalld#1004] opened 2022-08-03 19:05 UTC
Mint 21 Cinnamon Firewalld Config 1.1.1 gives an Error when clicking on Options / Runtime-to-Permanemt.
The Error says "Not_Enabled: enp2s0"
The enp2s0 name & number may be different on you PC.
I have no idea what to add or change.
Please fix ....

**Comment by erig0** [comment] 2022-08-04 12:39
Duplicate of #976.

**Closed by erig0** 2022-08-04 12:39 UTC
