### ISSUE TITLE
ipset with timeout create a set without the timeout flag

### ISSUE THREAD

**Issue by rabin-io** [firewalld/firewalld#1144] opened 2023-06-06 17:39 UTC
### What happened

The config of an set is not in sync with ipset

### How to reproduce it (as minimally and precisely as possible)

firewall-cmd --permanent --new-ipset=ipset --type=hash:ip --option='timeout=10'
systemctl restart firewalld

```
# ipset list
Name: ipset
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 10

# nft list ruleset | grep -C10 ipset

table inet firewalld {
  set ipset {
     type ipv4_addr
      flags interval
  }
```

### Firewalld Version

firewalld-0.9.3-13.el8.noarch

### Firewalld Backend

nftables

### Linux distribution

Red Hat Enterprise Linux 8.8 (Ootpa)

**Comment by erig0** [comment] 2023-06-06 19:33
Duplicate of #699.

**Closed** 2023-06-06 19:33 UTC
Labels: duplicate
