### ISSUE TITLE
Zone target doc still unclear. %%REJECT%% not the same as default!

### ISSUE THREAD

**Issue by BenjaminLefoul** [firewalld/firewalld#210] opened 2017-03-08 14:13 UTC
This has been changed several times:

https://github.com/t-woerner/firewalld/blob/7e7be5658c2b1a8aa130480ad8e1a7314c83bba9/doc/xml/firewalld.zone.xml#L134-L138
> `target="ACCEPT|%%REJECT%%|DROP"`
>> `Can be used to accept, reject or drop every packet that doesn't match any rule (port, service, etc.).
The ACCEPT target is used in <literal>trusted</literal> zone to accept every packet not matching any rule.`

>> **`The %%REJECT%% target is used in <literal>block</literal> zone to reject (with default firewalld reject type) every packet not matching any rule.`**

>> `The DROP target is used in <literal>drop</literal> zone to drop every packet not matching any rule.`

>> **`If the target is not specified, every packet not matching any rule will be rejected.`**

This suggests that `<zone target="%%REJECT%%">` and `<zone>` do the same thing.

However, in the first case, ICMP echo-requests are blocked (can't ping), and not in the second case.

**Comment by t-woerner** [comment] 2017-03-22 14:32
The default zone target is "{chain}_{zone}" (see firewall.core.base.DEFAULT_ZONE_TARGET). The default target is used if target is not set in a zone.

**Comment by BenjaminLefoul** [comment] 2017-03-22 14:59
So you can actually write not just:
`target="ACCEPT|%%REJECT%%|DROP"`

but:
`target="ACCEPT|%%REJECT%%|DROP|{chain}_{zone}|default"` with "default" being the same as not specifying the target in the zone xml file.

I really think this man page needs a clarification of these two targets: "{chain}_{zone}"  and "default".
Examples wouldn't hurt either.

Thank you!

**Comment by msjyoo** [comment] 2018-03-23 10:12
@t-woerner Hello, I also just spent some time trying to look for this concept of `default` target, since I wanted assurance that the public zone blocks all unwhitelisted ports. But I could not find any documentation of this anywhere.
```
$ sudo firewall-cmd --list-all --zone=public
public (active)
  target: default < ?? Does that mean block by default, or accept by default ??
```

There is no mention of this `default` target on:
http://www.firewalld.org/documentation/man-pages/firewalld.zone.html
http://www.firewalld.org/documentation/zone/options.html

Meanwhile in http://www.firewalld.org/documentation/man-pages/firewall-cmd.html:
```
--permanent [--zone=zone] --set-target=target

        Set the target of a permanent zone. target is one of: default, ACCEPT, DROP, REJECT 
```

But there's no documentation on what this `default` target is supposed to be.

**Comment by erinn** [comment] 2019-12-10 16:28
Have to say I just went through this process too trying to figure out exactly what 'default' meant. Looked for how to change default, doesn't appear possible. This whole thing is just a bit too confusing for something as important as a firewall in my opinion.

**Comment by erig0** [comment] 2020-03-25 17:05
Marking as duplicate of #590 as #590 has more information.

**Closed by erig0** 2020-03-25 17:05 UTC
Labels: documentation
