### ISSUE TITLE
ERROR: COMMAND_FAILED: 'handle'

### ISSUE THREAD

**Issue by tpgxyz** [firewalld/firewalld#819] opened 2021-07-09 11:33 UTC
**What happened**:
```
systemctl start firewalld.service
journalctl -xe -u firewalld 

Jul 09 13:28:02 omv-rockpro64 firewalld[135537]: ERROR: 'handle'
Jul 09 13:28:02 omv-rockpro64 firewalld[135537]: ERROR: COMMAND_FAILED: 'handle'
Jul 09 13:28:03 omv-rockpro64 firewalld[135537]: ERROR: 'handle'
Jul 09 13:28:03 omv-rockpro64 firewalld[135537]: ERROR: COMMAND_FAILED: 'handle'
```

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
```
[root@omv-rockpro64 tpg]# rpm -qf /usr/bin/firewall-cmd 
firewalld-0.9.4-2.noarch

[root@omv-rockpro64 tpg]# rpm -qf /usr/lib64/libmnl.so.0
lib64mnl0-1.0.4-5.aarch64

[root@omv-rockpro64 tpg]# rpm -qf /usr/lib64/libnftnl.so.11
lib64nftnl11-1.2.0-2.aarch64

[root@omv-rockpro64 tpg]# rpm -qf /usr/lib64/libnftables.so.1
lib64nftables1-0.9.9-4.aarch64

[root@omv-rockpro64 tpg]# rpm -qf /usr/lib64/libjansson.so.4
lib64jansson4-2.13.1-7.aarch64

[root@omv-rockpro64 tpg]# uname -a
Linux omv-rockpro64 5.12.13-server-clang-1omv4050 #1 SMP Fri Jun 25 13:46:02 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

```
**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`): 0.9.4
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`):  nftables
- OS (e.g: `cat /etc/os-release`): OpenMandriva LX cooker
- Others:

**Comment by erig0** [comment] 2021-07-12 19:29
Thanks for the report. Can you check `/var/log/firewalld` for previous errors? Did your config change since you're upgraded to v0.9.4? Does an earlier firewalld version (e.g. v0.9.3) produce the same errors?

**Comment by tpgxyz** [comment] 2021-07-13 19:35
Yes, previous version does produce same error.

Error is gone only when i remove `["handle"]` key from `self.rule_to_handle[rule_key] `https://github.com/firewalld/firewalld/blob/adb4ccd88e6c1fd460c9c674d89fdf89299c3970/src/firewall/core/nftables.py#L385

**Comment by erig0** [comment] 2021-07-13 20:06
> Error is gone only when i remove `["handle"]` key from `self.rule_to_handle[rule_key] `
> 
> https://github.com/firewalld/firewalld/blob/adb4ccd88e6c1fd460c9c674d89fdf89299c3970/src/firewall/core/nftables.py#L385

That completely breaks rule handle caching and will cause subsequent errors.

Do you have any other errors in your firewalld log? It might be worth truncating the log file and restart firewalld.
```
# truncate -s 0 /var/log/firewalld
# systemctl restart firewalld
```

**Comment by tpgxyz** [comment] 2021-07-17 21:47
@erig0 That is all i got

```
[root@omv-rockpro64 /]# systemctl stop firewalld.service 
[root@omv-rockpro64 /]# truncate -s 0 /var/log/firewalld
[root@omv-rockpro64 /]# systemctl restart firewalld.service 
[root@omv-rockpro64 /]# cat /var/log/firewalld
2021-07-17 23:47:11 ERROR: 'handle'
2021-07-17 23:47:11 ERROR: COMMAND_FAILED: 'handle'
2021-07-17 23:47:11 ERROR: 'handle'
2021-07-17 23:47:11 ERROR: COMMAND_FAILED: 'handle'
```

**Comment by erig0** [comment] 2021-07-19 16:55
I have no idea what's going on based on that little bit of log. Can you enable `--debug` for the daemon and also set `IndividualCalls=yes` in `/etc/firewalld/firewalld.conf` ?

**Comment by tpgxyz** [comment] 2021-07-20 16:19
Here is the output with enabled abouve options you have mentioned. [firewalld.txt](https://github.com/firewalld/firewalld/files/6849834/firewalld.txt)

**Comment by erig0** [comment] 2021-07-20 17:51
> Here is the output with enabled abouve options you have mentioned. [firewalld.txt](https://github.com/firewalld/firewalld/files/6849834/firewalld.txt)

This looks like libnftables is not returning the rule handles as expected. When firewalld initializes `python3-nftables` it requests this.

https://github.com/firewalld/firewalld/blob/3e285443584b4e502888721ee33724ff08abca50/src/firewall/core/nftables.py#L175-L177

It may be that you're hitting an architecture specific issue. I'll spin up an aarch64 VM and give it a try.

**Comment by erig0** [comment] 2021-08-31 14:52
@sochotnicky, anything in `/var/log/firewalld`? Maybe launch the `firewalld` daemon with `--debug=9` to get more info.

**Comment by sochotnicky** [comment] 2021-08-31 14:56
What looks like the problematic snippet from /var/log/firewalld:
```
2021-08-31 16:54:15 DEBUG3: <class 'firewall.core.nftables.nftables'>: calling python-nftables with JSON blob: {"nftables": [{"metainfo": {"json_schema_version": 1}}, {"insert": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_INPUT_ZONES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "wlp0s20f3"}}, {"goto": {"target": "filter_IN_public"}}]}}}]}
2021-08-31 16:54:15 DEBUG1: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/firewall/core/fw.py", line 902, in rules
    backend.set_rule(rule, self._log_denied)
  File "/usr/lib/python3.9/site-packages/firewall/core/nftables.py", line 388, in set_rule
    self.set_rules([rule], log_denied)
  File "/usr/lib/python3.9/site-packages/firewall/core/nftables.py", line 385, in set_rules
    self.rule_to_handle[rule_key] = output["nftables"][index][verb]["rule"]["handle"]
KeyError: 'handle'
```

The json obviously has no handle key

**Comment by erig0** [comment] 2021-08-31 15:13
> The json obviously has no handle key

There were no other errors/warnings in the log file? Can you share the whole log?

**Comment by sochotnicky** [comment] 2021-08-31 15:27
Attaching log with default config (I wiped my custom stuff to verify things are still the same)
[
[firewalld.txt](https://github.com/firewalld/firewalld/files/7085075/firewalld.txt)
](url)

**Comment by erig0** [comment] 2021-09-01 12:50
Can you verify your version of `nftables` is built with JSON support enabled?

Check for `libjansson` in `ldd` output.

```
$ ldd $(which nft) |grep jansson           
        libjansson.so.4 => /lib64/libjansson.so.4 (0x00007f339b963000)
```

**Comment by sochotnicky** [comment] 2021-09-01 12:56
> ldd $(which nft) |grep jansson
```
$ ldd $(which nft) |grep jansson  
	libjansson.so.4 => /usr/lib64/libjansson.so.4 (0x00007f0c10884000)
```

**Comment by sochotnicky** [comment] 2021-09-01 13:11
Perhaps a simple script using python-nftables might serve as a reproducer etc? As far as I understand things - libnftables is being initialized with `set_handle_output(True)` so *should* include handle in the output. FWIW I tried also adding `set_json_output(True)` to the init method just randomly.

I also added some logging just before the `self.rule_to_handle` assignment and the output really seems to get no handle for some reason.

**Comment by erig0** [comment] 2021-09-01 13:29
I bet you could reproduce it with the `nft -j` CLI as well. This seems to be an issue in either `libnftables` or in the messaging between userspace and kernel.

**Comment by sochotnicky** [comment] 2021-09-01 13:34
OK, I had CONFIG_ETHTOOL_NETLINK disabled, retrying with it...

**Comment by erig0** [comment] 2021-09-01 13:35
> OK, I had CONFIG_ETHTOOL_NETLINK disabled, retrying with it...

That doesn't seem likely. That looks like `ethtool`.

**Comment by sochotnicky** [comment] 2021-09-01 13:56
> > OK, I had CONFIG_ETHTOOL_NETLINK disabled, retrying with it...
> 
> That doesn't seem likely. That looks like `ethtool(8)`.

True - it didn't. I have other netlink config options enabled - with the exception of CONFIG_NETFILTER_NETLINK_HOOK which the doc string suggested is mostly useful for debugging. But I am trying to enable that now...

**Comment by sochotnicky** [comment] 2021-09-01 14:03
With cli I can't reproduce:
```
# nft -e -j add rule filter input ip protocol udp udp dport 50000
{"nftables": [{"add": {"rule": {"family": "ip", "table": "filter", "chain": "input", "handle": 6, "expr": [{"match": {"op": "==", "left": {"payload": {"protocol": "udp", "field": "dport"}}, "right": 50000}}]}}}]}
```

**Comment by sochotnicky** [comment] 2021-09-01 14:28
I've written a short python test script and can't reproduce with it either: https://gist.github.com/sochotnicky/8a0a1a47aaa4489ced77df63f6b554c0

Running it actually outputs:
```
# python test_nft.py
(0, {'nftables': [{'metainfo': {'json_schema_version': 1}}, {'add': {'rule': {'family': 'ip', 'table': 'filter', 'chain': 'input', 'expr': [{'match': {'op': '==', 'left': {'payload': {'protocol': 'udp', 'field': 'dport'}}, 'right': 50000}}], 'handle': 16}}}]}, '')
```
So - I am not sure where else to look but at this point I am back to thinking it's some quirk within firewalld

**Comment by erig0** [comment] 2021-09-01 14:41
Can you apply this patch and reproduce? It will dump the JSON at the index that is missing the handle.

```patch
diff --git a/src/firewall/core/nftables.py b/src/firewall/core/nftables.py                        
index ca5521a8804f..fa76b75e0dac 100644                                                           
--- a/src/firewall/core/nftables.py                                                               
+++ b/src/firewall/core/nftables.py                                                               
@@ -382,6 +382,8 @@ class nftables(object):                                                       
             if verb not in output["nftables"][index]:                                            
                 continue                                                                         
                                                                                                  
+            if "handle" not in output["nftables"][index][verb]["rule"]:                          
+                log.debug3("index = %u, JSON:\n%s", index, json.dumps(output["nftables"][index]))
             self.rule_to_handle[rule_key] = output["nftables"][index][verb]["rule"]["handle"]    
                                                                                                  
     def set_rule(self, rule, log_denied):                                                        
```

**Comment by sochotnicky** [comment] 2021-09-01 14:46
Log with the patch applied: [firewalld.gz](https://github.com/firewalld/firewalld/files/7092068/firewalld.gz)
I enabled `IndividualCalls=yes` to hopefully make it easier to read/debug but let me know if you want that changed

**Comment by erig0** [comment] 2021-09-01 14:50
> I've written a short python test script and can't reproduce with it either: https://gist.github.com/sochotnicky/8a0a1a47aaa4489ced77df63f6b554c0
> 
> Running it actually outputs:
> 
> ```
> # python test_nft.py
> (0, {'nftables': [{'metainfo': {'json_schema_version': 1}}, {'add': {'rule': {'family': 'ip', 'table': 'filter', 'chain': 'input', 'expr': [{'match': {'op': '==', 'left': {'payload': {'protocol': 'udp', 'field': 'dport'}}, 'right': 50000}}], 'handle': 16}}}]}, '')
> ```
> 
> So - I am not sure where else to look but at this point I am back to thinking it's some quirk within firewalld

Can you try this again, but use the verb `insert` instead of `add`?

**Comment by sochotnicky** [comment] 2021-09-01 14:54
Works in the same way as far as I can tell:
```
# python3 test_nft.py
(0, {'nftables': [{'metainfo': {'json_schema_version': 1}}, {'insert': {'rule': {'family': 'ip', 'table': 'filter', 'chain': 'input', 'expr': [{'match': {'op': '==', 'left': {'payload': {'protocol': 'udp', 'field': 'dport'}}, 'right': 50000}}], 'handle': 18}}}]}, '')
```

**Comment by erig0** [comment] 2021-09-01 15:12
I don't know. Your python snippet appears to do exactly the same thing that the nftables backed does.

The only oddity I see in your logs is that mixing of `iptables-legacy` with `iptables-nft`.
```
2021-09-01 16:44:32 DEBUG3: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables: probe for wait option (-w): ret=1, output="iptables v1.8.7 (nf_tables): table `filter' is incompatible, use 'nft' tool.
```

**Comment by sochotnicky** [comment] 2021-09-01 15:24
> I don't know. Your python snippet appears to do exactly the same thing that the nftables backed does.
> 
> The only oddity I see in your logs is the mixing of `iptables-legacy` with `iptables-nft`.
> 
> ```
> 2021-09-01 16:44:32 DEBUG3: <class 'firewall.core.ipXtables.ip4tables'>: /sbin/iptables: probe for wait option (-w): ret=1, output="iptables v1.8.7 (nf_tables): table `filter' is incompatible, use 'nft' tool.
> ```

That debug line went away after I switched from iptables being symlinked to /sbin/xtables-nft-multi and moved it to /sbin/xtables-legacy-multi  but the error/problem persists otherwise

**Comment by sochotnicky** [comment] 2021-09-01 15:54
I went and modified nftables/nftables.py to log actual settings for `get_handle_output()` and few other settings and log outputs etc. And I see handle being nicely returned for my script but not when executed from within firewalld. I am a bit stumped ...

**Comment by c-jason-kim** [comment] 2021-09-01 17:07
For what it's worth, I'm also experiencing this, also on Gentoo, also firewalld-1.0.1, nftables-1.0.0.  Had this issue for a few months, reverted to iptables until I had time to poke around. Definitely had it with firewalld-0.9.3, possibly 0.9.1.

Did similar testing as above with similar results, the only things I'd point out are 1) I was able to get my test to _not_ return a handle _only_ if the rule already existed, 2) 'nft monitor' doesn't show firewalld making _any_ nft changes, not just the ones that return the no handle error. It's as though the nft python library is in some dry run mode and simply returning the input (total conjecture, can't find anything that would do that).

**Comment by erig0** [comment] 2021-09-01 17:50
> 2) 'nft monitor' doesn't show firewalld making _any_ nft changes, not just the ones that return the no handle error. It's as though the nft python library is in some dry run mode and simply returning the input (total conjecture, can't find anything that would do that).

This particular issue might be explained by the firewalld nftables backend having rule de-duplication. If a rule is de-duplicated then it's not passed to libnftables.

However, in @sochotnicky's case we can see that the rule in indeed passed and a reply received. The below is from the log file they posted.
```
2021-09-01 16:44:32 DEBUG3: <class 'firewall.core.nftables.nftables'>: calling python-nftables with JSON blob: {"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"rule": {"family": "inet", "table": "firewalld", "chain": "mangle_PREROUTING", "expr": [{"jump": {"target": "mangle_PREROUTING_ZONES"}}]}}}]}
2021-09-01 16:44:32 DEBUG3: index = 1, JSON:
{"add": {"rule": {"family": "inet", "table": "firewalld", "chain": "mangle_PREROUTING", "expr": [{"jump": {"target": "mangle_PREROUTING_ZONES"}}]}}}
2021-09-01 16:44:32 DEBUG1: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/firewall/core/fw.py", line 902, in rules
    backend.set_rule(rule, self._log_denied)
  File "/usr/lib/python3.9/site-packages/firewall/core/nftables.py", line 390, in set_rule
    self.set_rules([rule], log_denied)
  File "/usr/lib/python3.9/site-packages/firewall/core/nftables.py", line 387, in set_rules
    self.rule_to_handle[rule_key] = output["nftables"][index][verb]["rule"]["handle"]
KeyError: 'handle'
```

**Comment by sochotnicky** [comment] 2021-09-01 17:59
@c-jason-kim Hmm, so we are both on Gentoo and yeah I can confirm I had similar issues in the past (just never looked into it too much). I just started digging after updating to recent versions and was hoping whatever quirks have been ironed out :-)

I have looked through Gentoo bugzilla and found nothing similar being reported. Perhaps we need to look what we have similar - apparently it's not a very common issue...

**Comment by erig0** [comment] 2021-09-01 18:13
Another area to probe is `json_events_cb()` in `libnftables`. That function is used to process the replies from the kernel and match them up with the JSON commands and add the `handle` to the JSON elements.

Unfortunately I've been unable to reproduce this on any of my environments: Ubuntu, RHEL, Fedora.

**Comment by c-jason-kim** [comment] 2021-09-01 19:21
> However, in @sochotnicky's case we can see that the rule is indeed passed and a reply received. 

Yes, I see that as well. It seems like firewalld is doing everything ok, it's sending the commands and receiving success responses and output. However it looks like nothing is actually happening when looking at `nft monitor`.

Feels like something with nftables, but everything I've tried outside firewalld seems to work fine. Continuing to poke at nft python client...

**Comment by erig0** [comment] 2021-09-01 20:04
Are you two sure nothing is interfering, e.g. SELinux?

**Comment by c-jason-kim** [comment] 2021-09-01 21:47
Same. I'm using a Gentoo kernel option that activates options recommended [here](https://kernsec.org/wiki/index.php/Kernel_Self_Protection_Project/Recommended_Settings). Didn't see anything obvious, but will try disabling and/or running a generic kernel when I get a chance. 

Different note, I've run strace on firewalld and my test scripts, I see the same netlink `socket`/`sendto`/`recvmsg`calls. Don't know how much that proves, but it seems like the netfilter calls are received and responded to by the kernel, they're just not doing anything.

**Comment by sochotnicky** [comment] 2021-09-02 06:26
Well - I basically disabled everything I could find (even things that really shouldn't need to be touched) and it made no difference. Let me know if you get somewhere @c-jason-kim :-)

**Comment by sochotnicky** [comment] 2021-09-02 10:01
Following the breadcrumbs in https://git.netfilter.org/nftables/tree/src/parser_json.c#n3895
`json_object_get(value, "metainfo")` does *not* return `NULL` when the command has no `metainfo` in firewalld case. Instead it returns same `value` so that `tmp2==value` after that line. 

So my current theory - this is some bug within jansson. When I tried using git master repo I instead start getting these errors:
```
firewall.errors.FirewallError: COMMAND_FAILED: 'python-nftables' failed: internal:0:0-0: Error: Schema version 32716 not supported, maximum supported version is 1
```
That's during parsing of commands from firewalld.

**Comment by erig0** [comment] 2021-09-02 11:31
firewalld does pass `metainfo`.

https://github.com/firewalld/firewalld/blob/36749f512bbcfc55f0e9e46354009073941d7363/src/firewall/core/nftables.py#L352-L357

**Comment by sochotnicky** [comment] 2021-09-02 11:42
> firewalld does pass `metainfo`.
> 
> https://github.com/firewalld/firewalld/blob/36749f512bbcfc55f0e9e46354009073941d7363/src/firewall/core/nftables.py#L352-L357

I am aware - but that actually matches even on the 2nd and further commands that are not `metainfo`

**Comment by sochotnicky** [comment] 2021-09-02 11:46
I shoved a bunch of logging statements through nftables and the log is basically like this:
```
json_parse array foreach iteration
value==tmp2 ?: 1
value: {"metainfo": {"json_schema_version": 1}}
tmp2: {"metainfo": {"json_schema_version": 1}}
json_parse array foreach iteration
value==tmp2 ?: 1
value: {"insert": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_INPUT_ZONES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "wlp0s20f3"}}, {"goto": {"target": "filter_IN_public"}}]}}}
tmp2: {"insert": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_INPUT_ZONES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "wlp0s20f3"}}, {"goto": {"target": "filter_IN_public"}}]}}}
```
On the second iteration tmp2 was supposed to be `NULL`.

**Comment by erig0** [comment] 2021-09-02 12:01
> I shoved a bunch of logging statements through nftables and the log is basically like this:
> 
> ```
> json_parse array foreach iteration
> value==tmp2 ?: 1
> value: {"metainfo": {"json_schema_version": 1}}
> tmp2: {"metainfo": {"json_schema_version": 1}}
> json_parse array foreach iteration
> value==tmp2 ?: 1
> value: {"insert": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_INPUT_ZONES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "wlp0s20f3"}}, {"goto": {"target": "filter_IN_public"}}]}}}
> tmp2: {"insert": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_INPUT_ZONES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "wlp0s20f3"}}, {"goto": {"target": "filter_IN_public"}}]}}}
> ```
> 
> On the second iteration tmp2 was supposed to be `NULL`.

I agree. That looks like it should be the case according to the jansson docs.

**Comment by erig0** [comment] 2021-09-02 12:09
> So my current theory - this is some bug within jansson (or perhaps memory corruption coming from nftables?). When I tried using git master repo I instead start getting these errors:
> 
> ```
> firewall.errors.FirewallError: COMMAND_FAILED: 'python-nftables' failed: internal:0:0-0: Error: Schema version 32716 not supported, maximum supported version is 1
> ```
> 
> That's during parsing of commands from firewalld.

nftables git master or jansson git master?

**Comment by sochotnicky** [comment] 2021-09-02 12:19
> > So my current theory - this is some bug within jansson (or perhaps memory corruption coming from nftables?). When I tried using git master repo I instead start getting these errors:
> > ```
> > firewall.errors.FirewallError: COMMAND_FAILED: 'python-nftables' failed: internal:0:0-0: Error: Schema version 32716 not supported, maximum supported version is 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That's during parsing of commands from firewalld.
> 
> nftables git master or jansson git master?

That's witch jansson git master. Though I've also been testing nftables mater - no difference. Interestingly there was a change yesterday to nftables json parser: https://git.netfilter.org/nftables/commit/ (but again - doesn't seem to help)

**Comment by erig0** [comment] 2021-09-02 12:30
> That's with jansson git master. Though I've also been testing nftables
mater - no difference.

Maybe it'll help with debugging if you disable optimizations, i.e.
compile with `-O0`. 

> Interestingly there was a change yesterday to nftables json parser:
https://git.netfilter.org/nftables/commit/ (but again - doesn't seem to
help)

That's for this bug:

  https://bugzilla.redhat.com/show_bug.cgi?id=1994141

**Comment by c-jason-kim** [comment] 2021-09-02 22:01
Going slightly crazy here... Added a bunch of fprintf statements to both libnftables and libjansson, best I can tell `json_object_get` is not getting called, no errors, no conflicting symbols, no idea what's going on.

Running `nft -j '{"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"table": {"family": "inet", "name": "firewalld"}}}]}'` with my debug statements I get:

**Comment by c-jason-kim** [comment] 2021-09-02 22:16
Going slightly crazy here... Added a bunch of fprintf statements to both libnftables in [parser_json.c](https://git.netfilter.org/nftables/tree/src/parser_json.c?h=v1.0.0#n3895) and libjansson in [value.c](https://github.com/akheron/jansson/blob/v2.13.1/src/value.c#L95), best I can tell `json_object_get`(jansson) is not getting called from `__json_parse`(nftables)... Other calls to `json_object_get` from other functions seem to work; no errors are returned, just the input json; couldn't find any conflicting symbols; and everything is fine with the `nft` cli.

Running `nft -j '{"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"table": {"family": "inet", "name": "firewalld"}}}]}'` with my debug statements I get:

> nlbuf: '{"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"table": {"family": "inet", "name": "firewalld"}}}]}
> '
> in __json_parse
> in json_object_get, key: 'nftables'
> tmp: '[{"metainfo": {"json_schema_version": 1}}, {"add": {"table": {"family": "inet", "name": "firewalld"}}}]'
> value: '{"metainfo": {"json_schema_version": 1}}'
> in json_object_get, key: 'metainfo'
> tmp2: '{"json_schema_version": 1}'
> in json_object_get, key: 'json_schema_version'
> value: '{"add": {"table": {"family": "inet", "name": "firewalld"}}}'
> in json_object_get, key: 'metainfo'
> tmp2: '(null)'
> in json_object_get, key: 'add'
> in json_object_get, key: 'table'
> in json_object_get, key: 'family'
> in json_object_get, key: 'name'

Running firewalld I get:

> nlbuf: '{"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"table": {"family": "inet", "name": "firewalld"}}}]}
> '
> in __json_parse
> in json_object_get, key: 'nftables'
> tmp: '[{"metainfo": {"json_schema_version": 1}}, {"add": {"table": {"family": "inet", "name": "firewalld"}}}]'
> value: '{"metainfo": {"json_schema_version": 1}}'
> tmp2: '{"metainfo": {"json_schema_version": 1}}'
> in json_object_get, key: 'json_schema_version'
> value: '{"add": {"table": {"family": "inet", "name": "firewalld"}}}'
> tmp2: '{"add": {"table": {"family": "inet", "name": "firewalld"}}}'
> in json_object_get, key: 'json_schema_version'
>

**Comment by sochotnicky** [comment] 2021-09-03 04:35
Yeah, I basically did the same with fprintf and had the same results - as if `json_object_get` was not called.

I ended up attaching gdb to python and playing around. What I found weird was that I could not step *into* `json_object_get` calls within `__json_parse` either (even though I was using my own debug build of nftables). But when I used `stepi` I eventually ended up with:
```
(gdb) si
0x00007ffff471c8c0 in json_object_get@plt ()
   from /data/temp/distdir/nftables/src/.libs/libnftables.so.1
(gdb) si
0x00007ffff5926630 in json_object_get () from /usr/lib64/libjson-c.so.5
```
Which looks wrong - the call should go to jansson lib - instead it ends up in libjson-c (which does have identically named method). Perhaps things are clashing in some way?

**Comment by sochotnicky** [comment] 2021-09-03 04:38
Yeah, I basically did the same with fprintf and had the same results - as if `json_object_get` was not called.

I ended up attaching gdb to python and playing around. What I found weird was that I could not step *into* `json_object_get` calls within `__json_parse` either (even though I was using my own debug build of nftables). But when I used `stepi` I eventually ended up with:
```
(gdb) si
0x00007ffff471c8c0 in json_object_get@plt ()
   from /data/temp/distdir/nftables/src/.libs/libnftables.so.1
(gdb) si
0x00007ffff5926630 in json_object_get () from /usr/lib64/libjson-c.so.5
```
Which looks wrong - the call should go to jansson lib - instead it ends up in libjson-c (which does have identically named method). Perhaps things are clashing in some way?

**Comment by sochotnicky** [comment] 2021-09-03 08:59
I am guessing this will fix things: https://github.com/akheron/jansson/commit/ca80d5127e56dd2ee056fdf3f4204017b78b89e0

Will test later unless someone beats me to it

**Comment by sochotnicky** [comment] 2021-09-03 09:19
Yeah, I can confirm that applying the patch & rebuilding nftables so that it uses versioned symbols resolved the issue of firewalld. Phew..

**Comment by erig0** [comment] 2021-09-03 11:37
@c-jason-kim, @sochotnicky, nice debugging work! Do you agree we can close this issue now?

Result: lack of symbol versioning caused a different library function form `libjsonc-c` to be used instead of the one from `jansson`. Fix is in jansson as noted by @sochotnicky, https://github.com/firewalld/firewalld/issues/819#issuecomment-912379171.

**Comment by sochotnicky** [comment] 2021-09-03 11:48
From my end - sure. JFYI I asked jansson dev/maintainer about releasing that fix in https://github.com/akheron/jansson/issues/460 since it's been merged for a while but distros are not consuming that fix until it's released.

**Comment by erig0** [comment] 2021-09-03 12:39
Closing. As per previous 2 comment this is a symbol versioning issues in `jansson` and `libjson-c`. It requires fixes in those libraries.

**Closed by erig0** 2021-09-03 12:39 UTC
Labels: insufficient data

**Comment by erig0** [comment] 2021-09-03 12:52
@sochotnicky, do you know how `libjson-c` was being pulled in to the dynamic library list? It's not used in RHEL/fedora.
```
[root@vm-bos-fedora ~]# ldd $(which nft)
        linux-vdso.so.1 (0x00007ffd811f6000)
        libnftables.so.1 => /lib64/libnftables.so.1 (0x00007f9812f1f000)
        libreadline.so.8 => /lib64/libreadline.so.8 (0x00007f9812ec7000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9812cf8000)
        libmnl.so.0 => /lib64/libmnl.so.0 (0x00007f9812cf0000)
        libnftnl.so.11 => /lib64/libnftnl.so.11 (0x00007f9812cbb000)
        libxtables.so.12 => /lib64/libxtables.so.12 (0x00007f9812ca7000)
        libjansson.so.4 => /lib64/libjansson.so.4 (0x00007f9812c95000)
        libgmp.so.10 => /lib64/libgmp.so.10 (0x00007f9812bf3000)
        libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f9812bc4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9812ff3000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f9812bbd000)
        libpcap.so.1 => /lib64/libpcap.so.1 (0x00007f9812b70000)
        libibverbs.so.1 => /lib64/libibverbs.so.1 (0x00007f9812b4d000)
        libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x00007f9812ac7000)
        libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00007f9812aa3000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9812a82000)
[root@vm-bos-fedora ~]# cat /etc/os-release 
NAME=Fedora
VERSION="34 (Thirty Four)"
```

**Comment by c-jason-kim** [comment] 2021-09-03 15:15
Damn, beat me to it. I tried searching for similar functions but messed up my readelf flags...

Anyway, it seems that json-c is being pulled in by python GI via libmount, explains why it works in nft and our simple test scripts. Thanks @sochotnicky and @erig0!

**Comment by sochotnicky** [comment] 2021-09-03 15:41
I didn't investigate why exactly but yes it was pulled in thorough gi imports within firewalld. I expect it's pretty random

**Comment by erig0** [comment] 2021-09-03 16:41
Thanks for the pointer about `libmount` (util-linux). AFAICS, it's actually `libcryptsetup` that pulls in `json-c`. RHEL/Fedora do not configure util-linux with `--with-cryptsetup` which is why they are unaffected.

At any rate, distributions should make sure they have the symbol version fixes for both `jansson` and `json-c`.

**Comment by c-jason-kim** [comment] 2021-09-03 18:03
Quick note for any poor Gentoo souls out there, I couldn't just apply that jansson commit as an eapply patch. Had to modify the jansson ebuild to add eautoreconf to resolve a libtool version mismatch. Not really sure why.

**Comment by erig0** [comment] 2021-09-03 18:43
> Quick note for any poor Gentoo souls out there, I couldn't just apply that jansson commit as an eapply patch. Had to modify the jansson ebuild to add eautoreconf to resolve a libtool version mismatch. Not really sure why.

I noticed the ebuild has a USE flag for libcryptsetup, which is what I thought was pulling in json-c. I thought it was disabled by default. Can you verify your build is using USE=libcrypesetup ?

**Comment by sochotnicky** [comment] 2021-09-03 19:03
It is disabled by default, I had cryptsetup use flag globally enabled however. Guess I'll go and rethink that decision :-)

**Comment by c-jason-kim** [comment] 2021-09-03 20:05
> > Quick note for any poor Gentoo souls out there, I couldn't just apply that jansson commit as an eapply patch. Had to modify the jansson ebuild to add eautoreconf to resolve a libtool version mismatch. Not really sure why.
> 
> I noticed the ebuild has a USE flag for libcryptsetup, which is what I thought was pulling in json-c. I thought it was disabled by default. Can you verify your build is using USE+=libcryptsetup ?

Sorry, I'm not sure which ebuild or use flag you're referring to... `libcryptsetup` flag doesn't exist, but there is a `cryptsetup`. Jansson/nftables/firewalld don't use either on my system. I do have `cryptsetup` enabled by default (for full disk encryption) which is used by `sys-apps/util-linux` which provides `libmount.so`.

**Comment by erig0** [comment] 2021-09-04 13:31
> > I noticed the ebuild has a USE flag for libcryptsetup, which is what I thought was pulling in json-c. I thought it was disabled by default. Can you verify your build is using USE+=libcryptsetup ?
> 
> Sorry, I'm not sure which ebuild or use flag you're referring to... `libcryptsetup` flag doesn't exist, but there is a `cryptsetup`.

I meant `USE+=cryptsetup`. Sorry for the confusion.

> Jansson/nftables/firewalld don't use either on my system. I do have `cryptsetup` enabled by default (for full disk encryption) which is used by `sys-apps/util-linux` which provides `libmount.so`.

If you don't need the `cryptsetup` for libmount/util-linux then I think you can get firewalld working by disabling the `cryptsetup` for that package.
e.g. in `/etc/portage/package.use`
```
sys-apps/util-linux        -cryptsetup
```

**Comment by sochotnicky** [comment] 2021-09-08 07:39
> Thanks for the pointer about `libmount` (util-linux). AFAICS, it's actually `libcryptsetup` that pulls in `json-c`. RHEL/Fedora do not configure util-linux with `--with-cryptsetup` which is why they are unaffected.
> 
> At any rate, distributions should make sure they have the symbol version fixes for both `jansson` and `json-c`. I filed bugs for RHEL and Fedora:
> 
>     * RHEL-8
>       
>       * jansson: https://bugzilla.redhat.com/show_bug.cgi?id=2001062
>       * json-c: https://bugzilla.redhat.com/show_bug.cgi?id=2001063
> 
>     * RHEL-9
>       
>       * jansson: https://bugzilla.redhat.com/show_bug.cgi?id=2001066
>       * json-c: https://bugzilla.redhat.com/show_bug.cgi?id=2001067
> 
>     * Fedora
>       
>       * jansson: https://bugzilla.redhat.com/show_bug.cgi?id=2001070
>       * json-c: https://bugzilla.redhat.com/show_bug.cgi?id=2001071

FYI I also filed a bug for Gentoo here:
https://bugs.gentoo.org/812119
