### ISSUE TITLE
Bug in firewalld/nftables

### ISSUE THREAD

**Issue by florianfa** [firewalld/firewalld#531] opened 2019-10-11 13:40 UTC
There seems to be a bug in nftables when using rich rules in firewalld that refer to ipsets with networks in CIDR notation.
This seems to occur only when the "hash:net" ipset contains networks (/24). When creating a "hash:net" ipset with hosts in CIDR notation (/32) everything works as expected.

The rich rule does not work and /var/log/firewalld shows:
2019-10-01 15:40:44 ERROR: Failed to apply rules. A firewall reload might solve the issue if the firewall has been modified using ip*tables or ebtables.
2019-10-01 15:40:44 ERROR: '/usr/sbin/nft add rule inet firewalld filter_IN_public_allow meta nfproto ipv4 ip saddr @example tcp dport 22 ct state new,untracked accept' failed:
2019-10-01 15:40:45 ERROR: Failed to apply rules. A firewall reload might solve the issue if the firewall has been modified using ip*tables or ebtables.
2019-10-01 15:40:45 ERROR: '/usr/sbin/nft insert rule inet firewalld raw_PREROUTING_ZONES iifname "ens192" goto raw_PRE_public' failed: Error: Could not process rule: No such file or directory
insert rule inet firewalld raw_PREROUTING_ZONES iifname "ens192" goto raw_PRE_public

See: https://bugs.centos.org/view.php?id=16518

**Comment by erig0** [comment] 2019-10-11 13:59
This appears to work on newer firewalld versions.
Can you add `--debug` to `/etc/sysconfig/firewalld`, reproduce, and then share the logs? It'll give more information.

**Comment by erig0** [comment] 2019-10-11 20:03
> ValueError: '/usr/sbin/nft add rule inet firewalld filter_IN_UIBK_allow meta nfproto ipv4 ip saddr @uibk_allow_ssh tcp dport 22 ct state new,untracked accept' failed:

This is the first error. It means the nft command failed, but there is no error message (don't know why). I'd guess it's actually an nftables bug. I'll try reproducing in my CentOS VM.

**Comment by Phurion** [comment] 2019-10-21 15:51
I'm having the same error
2019-10-21 08:38:23 DEBUG1: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/firewall/core/fw.py", line 903, in rules
    backend.set_rule(rule, self._log_denied)
  File "/usr/lib/python3.6/site-packages/firewall/core/nftables.py", line 349, in set_rule
    return self.__run(rule)
  File "/usr/lib/python3.6/site-packages/firewall/core/nftables.py", line 277, in __run
    _args_str, output))
ValueError: '/usr/sbin/nft add rule inet firewalld filter_IN_XXXX_allow meta nfproto ipv4 ip saddr @ssh_whitelist_ipv4 tcp dport XXX ct state new,untracked accept' failed: 

2019-10-21 08:38:23 ERROR: Failed to apply rules. A firewall reload might solve the issue if the firewall has been modified using ip*tables or ebtables.

This works just fine if the backend is set to iptables. 

Kernel: 4.18.0-80.11.2.el8_0.x86_64
Firewalld: 0.6.3
NFT: nftables v0.9.0 (Fearless Fosdick)
OS: CentOS Linux release 8.0.1905 (Core)

**Comment by Phurion** [comment] 2019-10-21 18:00
From messages:
kernel: nft[6734]: segfault at 2ac06 ip 00007f86a6dc4588 sp 00007ffcc94e7698 error 4 in libgmp.so.10.3.2[7f86a6daa000+94000]
kernel: Code: c1 48 29 c1 48 89 c8 75 44 4c 89 c2 48 8b 7f 08 48 8b 76 08 48 c1 fa 3f 48 89 d0 4c 31 c0 48 29 d0 eb 14 0f 1f 80 00 00 00 00 <48> 8b 14 c7 48 8b
 0c c6 48 39 ca 75 1b 48 83 e8 01 48 83 f8 ff 75
systemd[1]: Started Process Core Dump (PID 6735/UID 0).
ERROR: Failed to apply rules. A firewall reload might solve the issue if the firewall has been modified using ip*tables or ebtables.
ERROR: '/usr/sbin/nft add rule inet firewalld filter_IN_XXXXX_allow meta nfproto ipv4 ip saddr @XXXXX tcp dport XXXX ct state new,untracked accept' failed:
systemd-coredump[6736]: Process 6734 (nft) of user 0 dumped core.#012#012Stack trace of thread 6734:#012#0  0x00007f86a6dc4588 __gmpz_cmp (libgmp.so.10)#012#1 
 0x00007f86a74e13ba expr_value_cmp (libnftables.so.0)#012#2  0x00007f86a6a1f385 msort_with_tmp.part.0 (libc.so.6)#012#3  0x00007f86a6a1f0e1 msort_with_tmp.part.0 (libc.so.6)#012#4  0x00007f86a6a1f5e6 qsor
t_r (libc.so.6)#012#5  0x00007f86a74e2686 interval_map_decompose (libnftables.so.0)#012#6  0x00007f86a74dfb7f nlr_for_each_set.constprop.15 (libnftables.so.0)#012#7  0x00007f86a74e077f netlink_events_cb (
libnftables.so.0)#012#8  0x00007f86a74e0d68 netlink_echo_callback (libnftables.so.0)#012#9  0x00007f86a67e253e mnl_cb_run (libmnl.so.0)#012#10 0x00007f86a74e4fe2 mnl_batch_talk (libnftables.so.0)#012#11 0
x00007f86a74e7395 nft_netlink.isra.4 (libnftables.so.0)#012#12 0x00007f86a74e7991 nft_run_cmd_from_buffer (libnftables.so.0)#012#13 0x0000557f150bff2c main (nft)#012#14 0x00007f86a6a09813 __libc_start_mai
n (libc.so.6)#012#15 0x0000557f150c004e _start (nft)

**Comment by erig0** [comment] 2019-10-21 19:00
@Phurion, that makes in pretty clear that it's an nftables bug, not firewalld.

**Comment by erig0** [comment] 2019-10-21 19:02
Can you give your nftables version? `dnf info nftables`

**Comment by Phurion** [comment] 2019-10-21 19:51
@erig0 Sure it's 
Installed Packages
Name         : nftables
Epoch        : 1
Version      : 0.9.0
Release      : 8.el8
Arch         : x86_64
Size         : 741 k
Source       : nftables-0.9.0-8.el8.src.rpm
Repo         : @System
From repo    : anaconda
Summary      : Netfilter Tables userspace utillites
URL          : http://netfilter.org/projects/nftables/
License      : GPLv2
Description  : Netfilter Tables userspace utilities.

**Comment by m-erhardt** [comment] 2019-11-04 08:48
I am the creator of the original bug report at bugs.centos.org. Thanks @florianfa for opening this issue here at github.
Good to see that I'm not the only one facing this problem.

Just in case you need any more information from me feel free to ask.

**Comment by qs5779** [comment] 2019-11-16 16:54
I believe I am seeing the same issue on Archlinux. After adding an ipv6 ipset to my drop zone source, I get the following error.
sudo firewall-cmd --reload                  
Error: COMMAND_FAILED: '/usr/bin/nft add rule inet firewalld raw_PREROUTING_ZONES index 93 ip6 saddr @blacklist6 goto raw_PRE_drop' failed:

firewalld 0.7.2-1
nftables v0.9.2 (Scram)

**Comment by Phurion** [comment] 2019-11-19 16:48
@m-erhardt Can we get a link to the bug you put in? I would like to know if they plan on pushing out a newer version of nftables to CentOS 8

**Comment by m-erhardt** [comment] 2019-11-20 08:56
@Phurion the link is in the first post: https://bugs.centos.org/view.php?id=16518

**Comment by erig0** [comment] 2019-11-22 21:21
I was able to reproduce this on centos8-stream. I'm pretty confident it was fixed in nftables between v0.9.0 and v0.9.1 - specifically d9bf3d6de1d8 ("segtree: fix memleak in interval_map_decompose()"). A such, I'm closing this report.

--->8---

# gdb /usr/sbin/nft /var/lib/systemd/coredump/core.nft.0.ef9e406c55e14d6caf3ac386456f9caf.23235.1574456424000000
...
(gdb) bt  
#0  0x00007f9ed7646a45 in __gmpn_sub_n_coreisbr () from /usr/lib64/libgmp.so.10       
#1  0x00007f9ed76343f5 in __gmpz_sub () from /usr/lib64/libgmp.so.10                  
#2  0x00007f9ed7d447a5 in interval_map_decompose (set=0x557b441b7780) at segtree.c:876                                                                                       
#3  0x00007f9ed7d41b7f in nlr_for_each_set (nlr=<optimized out>, cb=0x7f9ed7d416c0 <rule_map_decompose_cb>, cache=0x557b441b6ab0, data=0x0) at monitor.c:193
#4  0x00007f9ed7d4277f in netlink_events_rule_cb (monh=0x7fffeeafe6c0, type=6, nlh=<optimized out>) at monitor.c:516                   
#5  netlink_events_cb (nlh=<optimized out>, data=data@entry=0x7fffeeafe6c0) at monitor.c:880                                                                                 
#6  0x00007f9ed7d42d68 in netlink_echo_callback (nlh=<optimized out>, data=<optimized out>) at monitor.c:911                                                                 
#7  0x00007f9ed704453e in mnl_cb_run () from /usr/lib64/libmnl.so.0          
#8  0x00007f9ed7d46fe2 in mnl_batch_talk (ctx=ctx@entry=0x7fffeeaff920, err_list=err_list@entry=0x7fffeeaff910) at mnl.c:273                                                 
#9  0x00007f9ed7d3a339 in netlink_batch_send (ctx=ctx@entry=0x7fffeeaff920, err_list=err_list@entry=0x7fffeeaff910) at netlink.c:1640                                        
#10 0x00007f9ed7d49395 in nft_netlink (nft=nft@entry=0x557b441b6a20, cmds=cmds@entry=0x7fffeeaff9d0, msgs=msgs@entry=0x7fffeeaff9c0, nf_sock=<optimized out>)                
    at libnftables.c:59                                                               
#11 0x00007f9ed7d49991 in nft_run_cmd_from_buffer (nft=0x557b441b6a20, buf=<optimized out>, buflen=<optimized out>) at libnftables.c:455                                     
#12 0x0000557b434fdf2c in main (argc=21, argv=0x7fffeeaffb68) at main.c:282

(gdb) frame 2
#2  0x00007f9ed7d447a5 in interval_map_decompose (set=0x557b441b7780) at segtree.c:876 
876     segtree.c: No such file or directory.

**Closed by erig0** 2019-11-22 21:21 UTC

**Comment by erig0** [comment] 2019-12-16 14:51
> I'm pretty confident it was fixed in nftables between v0.9.0 and v0.9.1 - specifically d9bf3d6de1d8 ("segtree: fix memleak in interval_map_decompose()").

It was verified that the above commit does _NOT_ fix this issue. However, it's still clear the issue is in nftables and not firewalld so I'm leaving this issue closed.
