### ISSUE TITLE
firewalld creates legacy ipsets with nftables backend

### ISSUE THREAD

**Issue by alanorth** [firewalld/firewalld#828] opened 2021-07-25 14:47 UTC
**What happened**:
firewalld creates legacy ipsets when using the nftables backend.

**What you expected to happen**:
firewalld does not create legacy ipsets when using the nftables backend.

**How to reproduce it (as minimally and precisely as possible)**:

```console
# firewall-cmd --get-ipsets

# ipset list
# 

# firewall-cmd --permanent --new-ipset=blocklist --type=hash:net --option=family=inet
# firewall-cmd --permanent --ipset=blocklist --add-entry=1.32.128.0/18
# firewall-cmd --permanent --add-rich-rule='rule source ipset=blocklist drop'
# firewall-cmd --reload
success
# ipset list
Name: blocklist
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 512
References: 0
Number of entries: 1
Members:
1.32.128.0/18
```

**Anything else we need to know?**:
I see it also creates an nft set as well:

```console
# nft list ruleset
table inet firewalld {
        set blocklist {
                type ipv4_addr
                flags interval
                elements = { 1.32.128.0/18 }
        }
...
table ip firewalld {
        set blocklist {
                type ipv4_addr
                flags interval
                elements = { 1.32.128.0/18 }
        }
```

**Environment**:
- Firewalld Version: 0.9.3-2
- Firewalld Backend: nftables
- OS: Debian GNU/Linux 11 (bullseye) (testing)
- Others: libnftables 0.9.8-3

Not sure if this is expected behavior, a bug in firewalld, or in Debian. Thanks!

**Comment by erig0** [comment] 2021-07-25 18:39
This is expected. Direct interface (iptables) users expect those sets to exist in ipset. Firewalld (v1.0.0+) will happily work without `ipset` existing. It's now an _optional_ depedency.

**Comment by erig0** [comment] 2021-07-25 18:41
Closing since this is expected behavior. But if you have questions, please ask. :)

**Closed by erig0** 2021-07-25 18:41 UTC
Labels: not a bug
