### ISSUE TITLE
RFE: support ipset on rich rule destination

### ISSUE THREAD

**Issue by jetojedno** [firewalld/firewalld#777] opened 2021-04-05 07:58 UTC
**What happened**:
```
# firewall-cmd --permanent --zone=fred   --add-rich-rule="
  rule family=ipv4 priority=-20
    source ipset=fred-drop     log prefix=\"fred.drop: \" level=warning limit value=5/s
    drop"
```
succeeds

```
# firewall-cmd --permanent --zone=fred   --add-rich-rule="
  rule family=ipv4 priority=-20
    destination ipset=fred-drop     log prefix=\"fred.drop: \" level=warning limit value=5/s
    drop"
```
fails with message `Error: INVALID_RULE: attribute 'ipset' outside of any element. Use 'rule <element> ipset= ...'.`

**What you expected to happen**:
both commands succeed

**How to reproduce it (as minimally and precisely as possible)**:
see above, but created ipset fred-drop & zone fred first

**Anything else we need to know?**:

**Environment**:
- firewall-cmd --version
0.8.2
- FirewallBackend=iptables
- ubuntu focal 20.04
- uname -a
Linux fred 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by erig0** [comment] 2021-04-05 12:14
That's because ipset is not supported on `destination` matches. See pages `firewalld.richlanguage(5)` and `firewalld.zone(5)`. Marking this as an enhancement request.

**Comment by darxriggs** [comment] 2022-02-15 14:34
Is this a duplicate of #706?

**Comment by erig0** [comment] 2022-02-15 19:40
> Is this a duplicate of #706?

Yes! I had forgotten this was already implemented. It's in `v1.0.0`.
Closing this report as a duplicate.

**Closed by erig0** 2022-02-15 19:40 UTC
Labels: feat
